import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { type ApplyOperation } from "../api";
import { runProgressPercent } from "../lib/applicationStatus";

export function ApplicationProgress({ operation, onControl }: { operation: ApplyOperation; onControl: (action: "resume" | "skip" | "cancel") => void }) {
  const active = ["queued", "running", "paused"].includes(operation.state);
  const [now, setNow] = useState(Date.now());
  useEffect(() => { if (!active) return; const id = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(id); }, [active]);
  const started = Date.parse(operation.application_started_at || operation.started_at || operation.updated_at);
  const ended = active ? now : Date.parse(operation.finished_at || operation.updated_at);
  const elapsed = Number.isFinite(started) && Number.isFinite(ended) ? `${Math.max(0, Math.floor((ended - started) / 1000))}s` : "—";
  const deadline = Date.parse(operation.application_deadline_at || "");
  const events = operation.events.filter((event, index, all) => index === 0 || event.message !== all[index - 1].message);
  return <section className="rounded-lg border border-line bg-panel p-4" aria-live="polite"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold capitalize">{operation.action} · {operation.state.replaceAll("_", " ")}</h2>{operation.current_application_id ? <Link className="text-sm text-accent underline" to={`/applications/${encodeURIComponent(operation.current_application_id)}`}>{operation.current_label || operation.current_application_id}</Link> : <p className="text-sm text-ink-muted">{operation.current_label || operation.message}</p>}{active && <p className="mt-1 text-sm">{operation.current_action_label || operation.message}{operation.current_field_label ? ` · ${operation.current_field_label}` : ""}</p>}</div><div className="flex gap-2 text-xs">{operation.state === "paused" && <><button className="rounded-md border border-line px-2" onClick={() => onControl("resume")}>Resume</button><button className="rounded-md border border-line px-2" onClick={() => onControl("skip")}>Skip item</button></>}{active && <button className="rounded-md border border-danger px-2 text-danger" onClick={() => onControl("cancel")}>Cancel</button>}</div></div>
    {operation.total > 0 ? <div role="progressbar" aria-valuenow={operation.processed} aria-valuemin={0} aria-valuemax={operation.total} className="mt-3 h-2 overflow-hidden rounded-full bg-line"><div className="h-full bg-accent" style={{ width: `${runProgressPercent(operation.processed, operation.total)}%` }} /></div> : active && <div role="progressbar" aria-label="Progress total unknown" className="rt-progress-indeterminate mt-3 h-2 rounded-full bg-accent-soft" />}
    <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-ink-muted"><span>{operation.total ? `${operation.processed}/${operation.total}` : `${operation.processed}/?`} processed</span><span>{operation.ready_for_review ?? operation.completed} ready for review</span><span>{operation.submitted} submitted</span><span>{operation.needs_input ?? operation.blocked} needs input</span><span>{operation.failed} failed</span></div>
    <details className="mt-3 border-t border-line pt-2 text-xs text-ink-muted"><summary className="cursor-pointer">Activity and timing</summary><p className="mt-2">Model: {operation.effective_model || "—"} · Stage: {operation.stage || "—"} · Elapsed: {elapsed}{active && Number.isFinite(deadline) ? ` · Deadline in ${Math.max(0, Math.floor((deadline - now) / 1000))}s` : ""}</p><p>Last activity: {operation.last_activity_at ? new Date(operation.last_activity_at).toLocaleString() : "—"} · Heartbeat: {operation.heartbeat_at ? new Date(operation.heartbeat_at).toLocaleString() : "—"}</p><ul className="mt-2 max-h-52 space-y-1 overflow-y-auto">{events.map((event, index) => <li key={`${event.at}-${index}`}>{event.at ? new Date(event.at).toLocaleTimeString() : ""} {event.message}</li>)}</ul>{Object.entries(operation.excluded ?? {}).length > 0 && <p className="mt-2">Excluded: {Object.entries(operation.excluded ?? {}).map(([id, reasons]) => `${id}: ${reasons.join(", ").replaceAll("_", " ")}`).join("; ")}</p>}</details>
  </section>;
}
