import { useState } from "react";
import type { Expansion } from "../api";
import { generateExpansion } from "../api";
import { describe } from "../lib/errors";
import { Button, ResultFrame } from "./ui";

/**
 * Stand-in for the Application experience tile when a run skipped expansion (the
 * default — only Apply needs it). One click writes it for this run with one model call.
 */
export function GenerateExperienceCard({
  jobId,
  ready,
  onGenerated,
  embedded = false,
}: {
  jobId: string;
  ready: boolean;
  onGenerated: (expansion: Expansion) => void;
  /** Inside the Tailor page's "Last result" tile: no box of its own. */
  embedded?: boolean;
}) {
  const [working, setWorking] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setWorking(true);
    setError(null);
    try {
      onGenerated(await generateExpansion(jobId));
    } catch (err) {
      setError(describe(err).detail);
    } finally {
      setWorking(false);
    }
  }

  return (
    <ResultFrame
      embedded={embedded}
      title="Application experience"
      description="Longer descriptions of each job for application-form paste fields. Not generated by default to save a model call; Apply makes them automatically when it needs them."
    >
      {error && <p className="mb-3 text-sm text-danger">{error}</p>}
      <Button disabled={!ready || working} onClick={() => void handleGenerate()}>
        {working ? "Generating…" : "Generate application experience"}
      </Button>
    </ResultFrame>
  );
}
