import { useState } from "react";
import type { Expansion } from "../api";
import { generateExpansion } from "../api";
import { describe } from "../lib/errors";

/**
 * Stand-in for the Application experience tile when a run skipped expansion (the
 * default — only Apply needs it). One click writes it for this run with one model call.
 */
export function GenerateExperienceCard({
  jobId,
  ready,
  onGenerated,
}: {
  jobId: string;
  ready: boolean;
  onGenerated: (expansion: Expansion) => void;
}) {
  const [working, setWorking] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setWorking(true);
    setError(null);
    try {
      onGenerated(await generateExpansion(jobId));
    } catch (err) {
      setError(describe(err).detail);
    } finally {
      setWorking(false);
    }
  }

  return (
    <section className="rounded-xl border border-line bg-panel p-5 shadow-sm">
      <h2 className="font-display text-xl font-semibold">Application experience</h2>
      <p className="mt-1 text-sm text-ink-muted">
        Longer descriptions of each job for application-form paste fields. Not generated by
        default to save a model call; Apply makes them automatically when it needs them.
      </p>
      {error && <p className="mt-2 text-sm text-danger">{error}</p>}
      <button
        type="button"
        disabled={!ready || working}
        onClick={() => void handleGenerate()}
        className="mt-3 rounded-lg border border-line px-3 py-2 text-sm font-medium hover:bg-paper disabled:opacity-50"
      >
        {working ? "Generating…" : "Generate application experience"}
      </button>
    </section>
  );
}
