"""Project-wide paths, model settings, and page-fit calibration constants.

Everything here is deliberately data rather than logic, so that tuning the tool's
behaviour — which model, how aggressively to shorten, how much text fits on a page —
never requires touching the pipeline code.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import platform
import re
import shutil
import sys
import threading
from collections.abc import Callable, Iterator
from concurrent.futures import Executor, Future
from contextlib import contextmanager
from contextvars import ContextVar, copy_context
from dataclasses import dataclass, replace
from pathlib import Path
from types import ModuleType
from typing import TYPE_CHECKING, Any, NamedTuple

from dotenv import load_dotenv

from . import library_seeds

if TYPE_CHECKING:
    from .content.industries import GuidanceSnapshot

# --------------------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------------------

# config.py lives at <root>/src/resume_tailor/config.py, so the root is three levels up.
PROJECT_ROOT = Path(__file__).resolve().parents[2]

load_dotenv(PROJECT_ROOT / ".env")


def _dir_from_env(var: str, default: Path) -> Path:
    """Resolve a directory that a deployment may relocate, defaulting to the repo layout.

    Exists for the container, where `data/`, `templates/` and `output/` are bind mounts
    that need not sit under the package root. Reading these from the environment keeps
    the same code working from a source checkout and from `/app` inside an image.
    """
    raw = os.environ.get(var)
    return Path(raw).expanduser().resolve() if raw else default


#: Deployment-relocatable storage roots. Unlike the DATA_DIR / TEMPLATES_DIR / etc.
#: views below, these are never rebound at runtime — they anchor the bind mounts (or
#: the repo layout) and the `workspaces/<id>/` tree that sits under each one.
DATA_ROOT = _dir_from_env("RESUME_TAILOR_DATA_DIR", PROJECT_ROOT / "data")
TEMPLATES_ROOT = _dir_from_env("RESUME_TAILOR_TEMPLATES_DIR", PROJECT_ROOT / "templates")
OUTPUT_ROOT = _dir_from_env("RESUME_TAILOR_OUTPUT_DIR", PROJECT_ROOT / "output")

#: Where the JD-extraction and relevance caches live. Split out from OUTPUT_DIR because
#: the web UI gives every run its own output directory, and a per-run cache would never
#: be hit — the whole point of those caches is that they survive across runs.
CACHE_ROOT = _dir_from_env("RESUME_TAILOR_CACHE_DIR", OUTPUT_ROOT)


def log_dir_setting() -> Path | None:
    """Where the app log goes: RESUME_TAILOR_LOG_DIR, "off" to disable, else OUTPUT_ROOT/logs."""
    raw = os.environ.get("RESUME_TAILOR_LOG_DIR", "").strip()
    if raw.lower() in {"off", "0", "none"}:
        return None
    return Path(raw).expanduser().resolve() if raw else OUTPUT_ROOT / "logs"

#: Name of the sub-directory holding per-workspace state under each root above.
WORKSPACES_DIRNAME = "workspaces"

#: Active-workspace views are supplied by __getattr__. Until registry bootstrap, the
#: process default uses the legacy single-slot layout under the storage roots.
# The active path views are provided by __getattr__ below.

#: Per-workspace run defaults, served by GET/PUT /api/settings.

#: Per-workspace vocabulary-library selection, overrides, and pending proposals. See
#: `libraries.py`. Lives beside `SETTINGS_PATH` rather than inside it — `settings.json`
#: is rewritten wholesale by `workspace.save_settings`, which would silently drop this
#: on any `PUT /api/settings` if the two shared a file.

#: Per-workspace application funnel state (discovered/screened/ready/submitted).
#: Sibling of `settings.json` for the same wholesale-rewrite reason as `LIBRARIES_PATH`.

#: Per-workspace form-filling answers (work auth, address, EEO, canned Q&A). Never part
#: of `MasterResume` — those fields are not resume content.

#: Per-workspace JD text + fill artifacts for the apply funnel (not the tailor job dirs).

#: Host browser remote-debugging endpoint (name kept for backward compatibility).
#: Docker reaches the host via `host.docker.internal` (the image sets
#: `RESUME_TAILOR_IN_DOCKER`); a host-side run uses loopback, where the app can start
#: the browser itself (`apply.driver.browser_launch`).
_IN_DOCKER = os.environ.get("RESUME_TAILOR_IN_DOCKER") == "1" or Path("/.dockerenv").exists()
CHROME_CDP_URL = os.environ.get(
    "CHROME_CDP_URL",
    "http://host.docker.internal:9222" if _IN_DOCKER else "http://127.0.0.1:9222",
)


def apply_fill_engine() -> str:
    """Which form-fill engine `fill.fill_application` uses: `legacy` or `verified`.

    Read at call time (not import time) so flipping the env var needs no restart of
    anything that already imported this module.
    """
    return os.getenv("APPLY_FILL_ENGINE", "legacy").strip().casefold()

#: The tagged template. GENERATED by scripts/build_template.py — do not hand-edit it;
#: fixes belong in the build script so they survive the next resume update.

#: The user's own resume as exported from Google Docs / Word. Strictly read-only: it is
#: both the build script's input and the visual baseline every render is compared against.

#: Confirmed field/section mapping for the active baseline (analyze → confirm → install).
#: Absent when the template was built with the legacy hard-coded heading path.

#: Named template snapshots (baseline + tagged + optional profile). Live paths stay single-slot;
#: activate copies a library entry into the live files.

#: The tagged cover-letter template. GENERATED by scripts/build_cover_template.py from
#: BASELINE_TEMPLATE_PATH — do not hand-edit it. Derived rather than uploaded so the letter's
#: letterhead, fonts, and page setup match the resume exactly; it therefore goes stale
#: whenever the resume template is reinstalled, which `web/template_ops` handles by
#: regenerating it inside the install path.

#: Sidecar recording ``cover_template._BUILDER_VERSION`` so code changes rebuild stale files.

#: Page margins for the cover letter — wider than the resume's cram-to-one-page setup.
COVER_MARGIN_INCHES = 1.0

#: Letterhead contact fields rendered on the cover letter (drops LinkedIn/GitHub).
COVER_CONTACT_FIELDS: tuple[str, ...] = ("location", "email", "phone")


def active_workspace_id() -> str | None:
    """Id of the active run's workspace, or the process default outside a run.

    None means the legacy single-slot layout: no registry has been bootstrapped, so
    every path view still resolves to its legacy location.
    """
    return _current_context().workspace_id


def workspace_paths(workspace_id: str) -> dict[str, Path]:
    """Every path `set_active_workspace` would bind for `workspace_id`, without binding.

    Exposed separately because create/duplicate/delete need to read or write one
    workspace's directories while a *different* workspace is active.
    """
    data = DATA_ROOT / WORKSPACES_DIRNAME / workspace_id
    templates = TEMPLATES_ROOT / WORKSPACES_DIRNAME / workspace_id
    output = OUTPUT_ROOT / WORKSPACES_DIRNAME / workspace_id
    cache = CACHE_ROOT / WORKSPACES_DIRNAME / workspace_id

    # Calibration is the one path that does not simply follow ROOT/workspaces/<id>: an
    # explicit RESUME_TAILOR_CALIBRATION_DIR override names a root of its own (mirroring
    # DATA_ROOT etc.), while the unset default nests under the workspace's own data dir
    # so the on-disk tree reads well — the alternative, data/calibration/workspaces/<id>,
    # is uglier for no benefit.
    calibration_env = os.environ.get("RESUME_TAILOR_CALIBRATION_DIR")
    calibration = (
        Path(calibration_env).expanduser().resolve() / WORKSPACES_DIRNAME / workspace_id
        if calibration_env
        else data / "calibration"
    )

    return {
        "DATA_DIR": data,
        "TEMPLATES_DIR": templates,
        "OUTPUT_DIR": output,
        "CACHE_DIR": cache,
        "CALIBRATION_DIR": calibration,
        "MASTER_RESUME_PATH": data / "master_resume.json",
        "SETTINGS_PATH": data / "settings.json",
        "SOURCE_STATUS_PATH": data / "source_status.json",
        "LIBRARIES_PATH": data / "libraries.json",
        "APPLICATIONS_PATH": data / "applications.json",
        "APPLICANT_PROFILE_PATH": data / "applicant_profile.json",
        "APPLICATIONS_OUTPUT_DIR": output / "applications",
        "DEFAULT_TEMPLATE_PATH": templates / "main_template.docx",
        "BASELINE_TEMPLATE_PATH": templates / "original_export.docx",
        "TEMPLATE_PROFILE_PATH": templates / "template_profile.json",
        "TEMPLATE_LIBRARY_DIR": templates / "library",
        "COVER_TEMPLATE_PATH": templates / "cover_template.docx",
        "COVER_TEMPLATE_META_PATH": templates / "cover_template.meta.json",
    }


def set_active_workspace(workspace_id: str, *, create_dirs: bool = False) -> str:
    """Set the process default workspace and its fit constants.

    Readers use `config.X` at call time, so a context-bound run keeps its own values.
    Workspace activation still follows the caller's `JobQueue.busy()` and
    `template_ops.LOCK` contract for template and registry mutations.
    """
    global _DEFAULT
    paths = workspace_paths(workspace_id)
    if create_dirs:
        for key in ("DATA_DIR", "TEMPLATES_DIR", "OUTPUT_DIR", "CACHE_DIR"):
            paths[key].mkdir(parents=True, exist_ok=True)

    calibration = _load_calibration(PDF_BACKEND, paths["CALIBRATION_DIR"], paths=paths)
    _DEFAULT = replace(_DEFAULT, workspace_id=workspace_id, paths=paths, calibration=calibration)
    return workspace_id


#: API-key names a user may save in the app (Settings -> Models) instead of `.env`.
SAVABLE_CREDENTIALS: tuple[str, ...] = (
    "ADZUNA_APP_ID",
    "ADZUNA_APP_KEY",
    "ANTHROPIC_API_KEY",
    "GEMINI_API_KEY",
    "GOOGLE_API_KEY",
    "LLM_API_KEY",
    "OLLAMA_API_KEY",
    "USAJOBS_API_KEY",
    "USAJOBS_EMAIL",
)


def credential(name: str) -> str:
    """An API key: the environment (`.env`) first, then the app's secret store.

    The environment wins so a key set for one shell or container overrides the saved
    one. A secret store that cannot be read counts as "not set".
    """
    value = os.environ.get(name, "")
    if value or name not in SAVABLE_CREDENTIALS:
        return value
    from resume_tailor.infra import secret_store

    try:
        return secret_store.get(f"api_key:{name}") or ""
    except secret_store.SecretStoreError:
        return ""


def anthropic_api_key() -> str:
    """Return the API key, failing with an actionable message if it is missing.

    Read lazily rather than at import time so that offline commands (validating the
    master resume, rendering dummy data) work without a key configured.
    """
    key = credential("ANTHROPIC_API_KEY")
    if not key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY is not set. Save it in Settings, or copy .env.example to "
            ".env and add it "
            "(get one at https://console.claude.com/settings/keys)."
        )
    return key


# --------------------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------------------

MODEL = "claude-sonnet-5"

#: Generous *starting* request — these are non-streaming calls whose real output is a few
#: KB of JSON, so this exists to prevent truncation, not to bound cost. It is no longer the
#: last word: `llm._OpenAICompatClient.request` escalates past it on the OpenAI-compatible
#: path when a response actually truncates (`finish == "length"`), up to `max_token_cap_for`.
#: A fixed ceiling stopped being enough once Gemini entered the mix — it counts thinking
#: tokens against `maxOutputTokens`, so a verbose stage could truncate outright with no
#: recovery. `MAX_TOKENS` still matters: it is what every *working* call is billed at, and
#: escalation only fires on what would otherwise be a hard failure (see `max_token_cap_for`).
#:
#: This is the *requested* ceiling, not necessarily the one sent. Anthropic refuses a
#: non-streaming request above 21,333 outright, so `max_tokens_for()` clamps that path —
#: read it before assuming a Claude run actually gets this budget. The Anthropic path never
#: escalates (see PROVIDER_MAX_TOKENS) — raising it means streaming, not this constant.
MAX_TOKENS = 32_000

#: Anthropic's hard limit for a non-streaming request: the SDK rejects anything where
#: `3600 * max_tokens / 128_000 > 600` with "Streaming is required...". It is a client-side
#: refusal, so an over-large value fails before a token is spent rather than degrading.
#: Lifting it means converting the call sites to streaming, not raising this number.
ANTHROPIC_NONSTREAMING_MAX_TOKENS = 21_333

#: Ceiling `max_tokens_for` will escalate an OpenAI-compatible stage up to, for a provider
#: with no entry in PROVIDER_MAX_TOKENS below. Ollama/LM Studio ids vary too much by model
#: to hardcode; this is a generous default that lets escalation help without guessing wrong.
MAX_TOKEN_CAP = 65_536

#: Per-origin override of MAX_TOKEN_CAP, keyed by `Backend.origin` (the word the user typed,
#: not the client shape `_backend` remaps to). Anthropic's entry mirrors
#: ANTHROPIC_NONSTREAMING_MAX_TOKENS so `max_token_cap_for` and `max_tokens_for` agree
#: without a separate anthropic-specific branch. Gemini 2.5+ output budgets run to 65,536.
PROVIDER_MAX_TOKENS: dict[str, int] = {
    "anthropic": ANTHROPIC_NONSTREAMING_MAX_TOKENS,
    "gemini": 65_536,
}

#: Escalation attempts `llm._OpenAICompatClient.request` makes on a truncated response
#: before giving up — bounded independently of the cap itself (a huge LLM_MAX_TOKENS
#: override should not turn one truncation into an unbounded doubling loop).
MAX_TOKEN_ESCALATIONS = 2

#: Pins BOTH the starting request and the escalation cap for every OpenAI-compatible stage,
#: overriding PROVIDER_MAX_TOKENS entirely. This is the "stop adapting, I already know the
#: right number" escape hatch — unset (the default) leaves the ceiling adaptive.
_LLM_MAX_TOKENS_ENV = os.environ.get("LLM_MAX_TOKENS")

#: Thinking depth. JD extraction and bullet rewriting are short, well-specified tasks;
#: "medium" is the cost/quality sweet spot and can be raised if rewrites come back bland.
#: Passed as `output_config={"effort": ...}` by both API calls — see MAX_TOKENS above.
#:
#: This is now only the *fallback* default; per-stage effort is resolved through
#: `effort_for()` below, because effort is where most of the bill actually goes.
EFFORT = "medium"


# --------------------------------------------------------------------------------------
# LLM backends
# --------------------------------------------------------------------------------------
#
# Measured: the prompts here are tiny (the largest call sends ~2,800 input tokens and
# returns ~1,250), so at Sonnet rates a run should cost ~$0.03 per call. It bills ~$0.16.
# The difference is reasoning tokens, drawn from MAX_TOKENS and billed as output. Roughly
# 80% of the cost is thinking depth, not the model — which is why EFFORT is a per-stage
# knob below and not a single constant.
#
# `--model` then addresses the other 20% by routing stages at different backends entirely.

#: The seven stages that call a model. Each resolves independently, so the cheap, safe
#: calls (extract, score, facets, skills) can run on a free backend while rewriting — where
#: the fabrication guard lives and where model quality actually shows — stays on Claude.
#: `expand` produces application-form experience descriptions; it follows the profile
#: like the others (Ollama under `ollama`/`hybrid`, Claude under `claude`).
#: `facets` picks project tech tags and coursework for the posting (same risk class as score).
#: `skills` selects/ranks a tailored skills list from a closed pool of the resume's own
#: evidence (same "model selects, code enforces" risk class as facets).
#: `cover` drafts the cover letter's body paragraphs from the *tailored* bullets. It is the
#: only stage that writes free prose, so it carries the widest guard surface (fabrication,
#: numbers, AI tells, word band) — see `coverletter._accept_letter`.
#: `review` is an opt-in hiring-manager pass over already-tailored bullets; suggested
#: rewrites are fabrication-checked and never auto-applied — see `review.review_bullets`.
#: `answer` drafts free-text application-form answers (guarded by `coverletter.check_claims`);
#: the only LLM call inside `resume_tailor.apply`.
PURPOSES = (
    "extract",
    "score",
    "rewrite",
    "expand",
    "facets",
    "skills",
    "cover",
    "review",
    "answer",
)

#: Providers `parse_spec` recognises as a leading segment. Anything else is read as a bare
#: model name, which matters more than it looks: `gemma4:cloud` contains a
#: colon, so a naive split would take "gemma4" for a provider.
PROVIDERS = ("anthropic", "openai", "ollama", "lmstudio", "gemini")

#: Origins that require a credential. `api_key_for` treats every other origin's key as
#: optional (a local server, or a hosted one that authenticates some other way) — Gemini's
#: OpenAI-compat shim rejects an unauthenticated request outright, so a missing key should
#: fail loudly before a call is made, not surface as an opaque 401 mid-run.
PROVIDERS_REQUIRING_KEY = frozenset({"gemini"})

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434/v1")

#: Ollama Cloud's own OpenAI-compatible endpoint, for the `ollama-cloud` profile: the same
#: hosted models the local daemon forwards `:cloud` tags to, reached without installing
#: anything. Needs `OLLAMA_API_KEY` (see `requires_key`).
OLLAMA_CLOUD_BASE_URL = os.environ.get("OLLAMA_CLOUD_BASE_URL", "https://ollama.com/v1")

#: Ollama Cloud runs this on Ollama's servers, so laptop VRAM is irrelevant. Note the
#: colon in the tag — see `parse_spec`.
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "gemma4:cloud")

#: Backend for one-off web-UI actions that are not part of a tailoring run (today: the
#: import wizard's tag-suggestion pass). Deliberately independent of `_ACTIVE` and of
#: `backend_for`'s claude fallback — a background convenience call must not bill a paid
#: API by accident. See `pinned()`.
ONE_OFF_PROFILE = os.environ.get("ONE_OFF_PROFILE", "ollama")

#: LM Studio's local OpenAI-compatible server (Developer → Start Server). Default port 1234.
LMSTUDIO_BASE_URL = os.environ.get("LMSTUDIO_BASE_URL", "http://localhost:1234/v1")

#: Must match the exact model id shown in LM Studio for the loaded model — not an
#: Ollama-style tag. Override via LMSTUDIO_MODEL before selecting the lmstudio profile.
LMSTUDIO_MODEL = os.environ.get("LMSTUDIO_MODEL", "local-model")

#: Google's OpenAI-compatible endpoint for Gemini. Same `_OpenAICompatClient` path as
#: Ollama/LM Studio — Gemini just needs its own base URL, model default, and (unlike the
#: other two) an actual key. See PROVIDERS_REQUIRING_KEY.
GEMINI_BASE_URL = os.environ.get(
    "GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta/openai"
)

#: AI Studio's free-tier workhorse: fine for the four structured-judgement stages
#: (extract/score/facets/expand) and capable enough for rewrite too. Override via
#: GEMINI_MODEL if the id changes or a heavier/lighter model fits better.
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.5-flash")

#: HTTP wait for one LLM completion. Local servers (LM Studio) rewriting a full
#: bullet batch can take well past five minutes; 900s leaves headroom without
#: hanging forever on a wedged daemon.
LLM_TIMEOUT = float(os.environ.get("LLM_TIMEOUT", "900"))

#: How to ask for JSON on the OpenAI-compatible path.
#:
#: "prompt"  — schema in the system prompt + `response_format: json_object`.
#: "schema"  — additionally send `response_format: json_schema` with a strict schema.
#:
#: `_STRUCTURED_MODE_ENV` is `None` when unset, which matters: it lets `structured_mode_for`
#: distinguish "nothing configured" (fall back to the per-provider default below) from "the
#: user explicitly asked for prompt mode" (honour it globally, even for Gemini). `
#: LLM_STRUCTURED_MODE` stays as the plain default-applied constant so existing readers of
#: it are unaffected.
_STRUCTURED_MODE_ENV = os.environ.get("LLM_STRUCTURED_MODE")
LLM_STRUCTURED_MODE = _STRUCTURED_MODE_ENV or "prompt"

#: Per-origin override of the default above, used by `structured_mode_for` when
#: `_STRUCTURED_MODE_ENV` is unset. "prompt" (the global default) exists because it is what
#: was *measured* to work against Ollama Cloud: it accepts `json_schema` and silently
#: ignores it, returning HTTP 200 with markdown prose, so sending it there is a round trip
#: that always fails against finite quota. Gemini's shim genuinely enforces `json_schema`,
#: so it gets the stronger default; every other origin keeps "prompt" via dict.get.
PROVIDER_STRUCTURED_MODE: dict[str, str] = {"gemini": "schema"}

#: Per-stage reasoning depth. Extraction is structured matching against a supplied
#: vocabulary and scoring is 39 independent judgements — neither is reasoning-hard, and
#: both were paying for "medium". Rewriting keeps it: that is the call where thinking
#: shows up in the output.
DEFAULT_EFFORT: dict[str, str] = {
    "extract": os.environ.get("LLM_EFFORT_EXTRACT", "low"),
    "score": os.environ.get("LLM_EFFORT_SCORE", "low"),
    "rewrite": os.environ.get("LLM_EFFORT_REWRITE", "medium"),
    "expand": os.environ.get("LLM_EFFORT_EXPAND", "medium"),
    "facets": os.environ.get("LLM_EFFORT_FACETS", "low"),
    "skills": os.environ.get("LLM_EFFORT_SKILLS", "low"),
    # Prose under a word band with a voice to match — closer to rewrite than to selection.
    "cover": os.environ.get("LLM_EFFORT_COVER", "medium"),
    # Adversarial judgement over supplied text; no fabrication risk once guarded.
    "review": os.environ.get("LLM_EFFORT_REVIEW", "low"),
    # Application-form free text; guard-checked like cover, short answers.
    "answer": os.environ.get("LLM_EFFORT_ANSWER", "low"),
}

#: How many independent extractions `jd.extract_consensus` runs and votes over. Measured
#: on one posting at `temperature=0` (already the default — see `llm.py`'s `_OpenAICompatClient`):
#: identical JD, identical resume, 8 extractions still ranged 3/10 to 6/11 must-have coverage,
#: because `canonical` is free text the model re-derives per call and the denominator itself
#: (how many must-haves the posting has) was not stable either. Voting on the majority reading
#: of each verbatim `phrase` fixes this without inventing anything the model did not itself
#: propose — see `extract_consensus`'s docstring for the exact rule. 3 is the minimum that
#: produces a majority; 1 restores today's single-call behaviour exactly.
EXTRACT_CONSENSUS_RUNS = int(os.environ.get("LLM_EXTRACT_CONSENSUS_RUNS", "3"))
#: Set only when the environment pins the vote count; otherwise it follows the backend.
_EXTRACT_RUNS_PINNED = bool(os.environ.get("LLM_EXTRACT_CONSENSUS_RUNS"))
#: Extraction origins stable enough that one call is the default: the frontier APIs
#: rarely disagree with themselves, and a vote there triples a paid call. Local models
#: (ollama, lmstudio) and generic OpenAI-compatible servers keep the 3-way vote.
SINGLE_EXTRACT_ORIGINS: frozenset[str] = frozenset({"anthropic", "gemini"})


def extract_runs(requested: int | None = None) -> int:
    """Vote count for JD extraction: ``requested`` when set (>0), else the env value
    when pinned, else 1 for `SINGLE_EXTRACT_ORIGINS` and `EXTRACT_CONSENSUS_RUNS` for the
    rest. Resolve inside the run's routing (`resolve`/`pinned`): it reads the extract
    stage's backend. The count is part of the extraction cache file name, so a change
    never replays a vote of a different size."""
    if requested:
        return requested
    if _EXTRACT_RUNS_PINNED:
        return EXTRACT_CONSENSUS_RUNS
    backend = backend_for("extract")
    origin = backend.origin or backend.provider
    return 1 if origin in SINGLE_EXTRACT_ORIGINS else EXTRACT_CONSENSUS_RUNS

_ANTHROPIC_DEFAULT = f"anthropic:{MODEL}"
_OLLAMA_DEFAULT = f"ollama:{OLLAMA_MODEL}"
_OLLAMA_CLOUD_DEFAULT = f"ollama:{OLLAMA_MODEL}@{OLLAMA_CLOUD_BASE_URL}"
_LMSTUDIO_DEFAULT = f"lmstudio:{LMSTUDIO_MODEL}"
_GEMINI_DEFAULT = f"gemini:{GEMINI_MODEL}"

#: Named shorthands for `--model`. `hybrid` is the one worth understanding: the two cheap,
#: low-risk calls move to the free backend while rewriting stays on Claude, which is where
#: an invented tool or a restated number would actually cost you. `ollama-cloud` is
#: `ollama` with every stage pinned to OLLAMA_CLOUD_BASE_URL — same tag, no local daemon.
#: `lmstudio` mirrors `ollama` but points at LM Studio's local server (see
#: LMSTUDIO_BASE_URL). `gemini` is the same shape again, pointed at GEMINI_BASE_URL —
#: there is deliberately no `gemini-hybrid`; mixing Gemini with Claude is one
#: `--rewrite-model claude-sonnet-5` away and a second `*-hybrid` profile would make the
#: existing one ambiguous about which "hybrid" it means.
MODEL_PROFILES: dict[str, dict[str, str]] = {
    "claude": dict.fromkeys(PURPOSES, _ANTHROPIC_DEFAULT),
    "ollama": dict.fromkeys(PURPOSES, _OLLAMA_DEFAULT),
    "ollama-cloud": dict.fromkeys(PURPOSES, _OLLAMA_CLOUD_DEFAULT),
    "lmstudio": dict.fromkeys(PURPOSES, _LMSTUDIO_DEFAULT),
    "gemini": dict.fromkeys(PURPOSES, _GEMINI_DEFAULT),
    "hybrid": {
        "extract": _OLLAMA_DEFAULT,
        "score": _OLLAMA_DEFAULT,
        "rewrite": _ANTHROPIC_DEFAULT,
        # Expansion is guard-protected and advisory (never shipped as the .docx), so it
        # rides the free backend even though it is generative — flip to Claude if quality
        # drops under Ollama.
        "expand": _OLLAMA_DEFAULT,
        # Facets is selection-only (pools supplied; code enforces budgets), same risk class
        # as score — keep it on the free backend under hybrid.
        "facets": _OLLAMA_DEFAULT,
        # Skills is also selection-only from a supplied closed pool (code enforces
        # membership) — same risk class as facets.
        "skills": _OLLAMA_DEFAULT,
        # The cover letter is free prose in a specific voice, which is exactly where a
        # weaker model shows. It is also advisory (a human reads it before sending) and
        # guard-protected, so it rides the free backend by default like expand — flip it
        # to Claude if the letters read flat.
        "cover": _OLLAMA_DEFAULT,
        # Review is adversarial judgement over already-guarded text — free backend.
        "review": _OLLAMA_DEFAULT,
        # Application answers are guard-checked and short — free backend.
        "answer": _OLLAMA_DEFAULT,
    },
}


def is_local_url(url: str | None) -> bool:
    """Whether ``url`` points at this machine or the local network.

    Localhost, loopback, ``host.docker.internal``, ``*.local`` and private (RFC 1918,
    link-local) addresses count as local. Anything else, such as Ollama Cloud's
    ``https://ollama.com/v1``, is a remote service: it needs a key, is billed by its
    provider, and is not something the student "starts".
    """
    import ipaddress
    from urllib.parse import urlsplit

    if not url:
        return False
    host = (urlsplit(url if "//" in url else f"//{url}").hostname or "").lower()
    if not host:
        return False
    if host in {"localhost", "host.docker.internal"} or host.endswith((".localhost", ".local")):
        return True
    try:
        address = ipaddress.ip_address(host)
    except ValueError:
        return False
    return address.is_loopback or address.is_private or address.is_link_local


def is_ollama_cloud(url: str | None) -> bool:
    """Whether ``url`` is Ollama Cloud's hosted API (the host of OLLAMA_CLOUD_BASE_URL).

    Matched on the exact host, not on "any remote address": a self-hosted Ollama on a LAN
    hostname like ``gpu-box:11434`` is not local by `is_local_url`'s rules, yet needs no
    key, and must not start failing for want of one.
    """
    from urllib.parse import urlsplit

    def _host(value: str) -> str:
        return (urlsplit(value if "//" in value else f"//{value}").hostname or "").lower()

    cloud = _host(OLLAMA_CLOUD_BASE_URL)
    return bool(url) and bool(cloud) and _host(url) == cloud


def requires_key(origin: str, base_url: str | None) -> bool:
    """Whether a backend fails without a credential — the one rule `credential_gaps` and
    `llm.client_for` share. Gemini always; Ollama only when pointed at Ollama Cloud's API
    (the local daemon authenticates through `ollama signin` instead)."""
    if origin in PROVIDERS_REQUIRING_KEY:
        return True
    return origin == "ollama" and is_ollama_cloud(base_url)


class Backend(NamedTuple):
    """A fully resolved routing decision for one stage.

    `provider` is the **client shape** `llm.client_for` dispatches on — `anthropic` or
    `openai`, since Ollama/LM Studio/Gemini all speak the same `/chat/completions` shape
    once remapped. `origin` is the **word the user actually typed** (`ollama`, `lmstudio`,
    `gemini`, or `""` for `anthropic`/`openai` specs, which need no disambiguation) — it
    survives the remap so credentials, structured-output policy, and token caps can still
    tell three same-shaped backends apart. Defaulted so existing hand-built `Backend(...)`
    call sites (tests, `report.py`) keep working unchanged.
    """

    provider: str
    model: str
    base_url: str | None
    effort: str
    origin: str = ""

    def label(self) -> str:
        """Human-readable identity, for the run report."""
        return f"{self.origin or self.provider}:{self.model}"


def parse_spec(spec: str) -> tuple[str, str, str | None]:
    """Parse `provider:model[@base_url]` into its parts.

    **Split on the first colon only.** Ollama tags embed colons, so the default model
    `ollama:gemma4:cloud` must yield model `gemma4:cloud`; splitting
    anywhere else breaks the primary use case rather than an edge case.

    A leading segment that is not a known provider means the whole string is a model name
    (`gemma4:cloud` on its own, or `claude-sonnet-5`). The provider is then inferred:
    Anthropic for `claude-*`, Ollama otherwise, since those are the two ways a bare name is
    realistically supplied. Stage overrides under an `lmstudio`/`ollama` profile are
    rebound in `resolve` before this runs so LM Studio ids like `google/gemma-4-12b` do
    not silently become Ollama.
    """
    spec = spec.strip()
    if not spec:
        raise ValueError("Empty model spec.")

    base_url: str | None = None
    if "@" in spec:
        spec, _, base_url = spec.partition("@")
        base_url = base_url or None

    head, sep, tail = spec.partition(":")
    if sep and head.lower() in PROVIDERS:
        provider, model = head.lower(), tail
    else:
        model = spec
        provider = "anthropic" if model.lower().startswith("claude") else "ollama"

    if not model:
        raise ValueError(f"Model spec {spec!r} names a provider but no model.")
    return provider, model, base_url


def _has_explicit_provider(spec: str) -> bool:
    """True when the first `:` segment is a known provider (not part of a model tag)."""
    spec = spec.strip()
    if "@" in spec:
        spec = spec.partition("@")[0]
    head, sep, _tail = spec.partition(":")
    return bool(sep and head.lower() in PROVIDERS)


def _bind_bare_override(override: str, profile_spec: str) -> str:
    """Keep a bare model id on the profile stage's local backend.

    UI overrides are often LM Studio ids (`google/gemma-4-12b`) with no `lmstudio:`
    prefix. Without rebinding, `parse_spec` would infer Ollama and hit :11434. Explicit
    `provider:...` specs and bare `claude-*` names are left alone. When the profile stage
    is Anthropic (e.g. hybrid rewrite), bare non-Claude names still fall through to the
    historical Ollama default.
    """
    override = override.strip()
    if _has_explicit_provider(override) or override.lower().startswith("claude"):
        return override

    provider, _model, base = parse_spec(profile_spec)
    if provider not in ("ollama", "lmstudio", "gemini"):
        return override

    model, o_base = override, None
    if "@" in override:
        model, _, o_base = override.partition("@")
        o_base = o_base or None
    bound = f"{provider}:{model}"
    final_base = o_base or base
    if final_base:
        bound = f"{bound}@{final_base}"
    return bound


def provider_stages(profile: str, provider: str) -> tuple[str, ...]:
    """Which stages of `profile` route to `provider`, so a UI-supplied tag can repoint them.

    Exists because e.g. `OLLAMA_MODEL` is read once at import and baked into
    `MODEL_PROFILES`, which left the web UI able to pick the *profile* but not the *tag* —
    changing model meant editing `.env` and restarting the server. The web layer turns the
    answer here into per-stage `resolve(overrides=...)` entries.

    Returns stages, not a rewritten profile dict, precisely so `hybrid` keeps working:
    its `rewrite` stage is Anthropic and must not be repointed at an Ollama tag. A raw
    spec (not a profile name) is all-or-nothing — every stage already shares it.

    Checks the *pre-remap* provider word (what `parse_spec` returns), not `Backend.origin`
    — this runs before any `Backend` exists.
    """
    specs = MODEL_PROFILES.get(profile.strip())
    if specs is None:
        try:
            spec_provider = parse_spec(profile)[0]
        except ValueError:
            return ()
        return PURPOSES if spec_provider == provider else ()
    return tuple(p for p in PURPOSES if parse_spec(specs[p])[0] == provider)


def ollama_stages(profile: str) -> tuple[str, ...]:
    """`provider_stages(profile, "ollama")` — kept as a thin wrapper for existing callers."""
    return provider_stages(profile, "ollama")


def _default_base(provider: str) -> str | None:
    """The env-default base URL for a provider word, or None when it has none.

    Shared by `_backend` and `credential_gaps` so the address a key check looks at is the
    address the call will actually go to.
    """
    return {
        "ollama": OLLAMA_BASE_URL,
        "lmstudio": LMSTUDIO_BASE_URL,
        "gemini": GEMINI_BASE_URL,
    }.get(provider)


def _backend(spec: str, purpose: str, effort: str | None) -> Backend:
    """Resolve a raw spec into a Backend, remapping local aliases to OpenAI-compat."""
    provider, model, base_url = parse_spec(spec)
    origin = provider
    # All three speak /v1/chat/completions; keep distinct env defaults so switching
    # profiles does not require editing a shared base URL.
    if provider in ("ollama", "lmstudio", "gemini"):
        provider, base_url = "openai", base_url or _default_base(provider)
    return Backend(
        provider=provider,
        model=model,
        base_url=base_url,
        effort=effort or DEFAULT_EFFORT.get(purpose, EFFORT),
        origin=origin,
    )


#: Compatibility view of the process default routing. Context-bound runs have their own map.
_ACTIVE: dict[str, Backend] = {}  # compatibility view of default routing


def _backends_for(
    profile: str | None,
    *,
    overrides: dict[str, str] | None = None,
    effort: str | None = None,
) -> dict[str, Backend]:
    """Shared spec-resolution logic behind both `resolve()` and `pinned()`.

    `profile` is a name from `MODEL_PROFILES` or a raw spec applied to every stage.
    `overrides` routes individual stages (`{"rewrite": "claude-sonnet-5"}`).
    A bare model id in an override keeps the profile stage's ollama/lmstudio backend
    (so `lmstudio` + `google/gemma-4-12b` does not silently call Ollama).
    """
    profile = (profile or "claude").strip()

    if profile in MODEL_PROFILES:
        specs = dict(MODEL_PROFILES[profile])
    elif ":" in profile or "@" in profile or profile.lower().startswith("claude"):
        specs = dict.fromkeys(PURPOSES, profile)
    else:
        raise ValueError(
            f"Unknown model profile {profile!r}. Use one of "
            f"{', '.join(sorted(MODEL_PROFILES))}, or a spec like "
            f"'ollama:{OLLAMA_MODEL}'."
        )

    for purpose, spec in (overrides or {}).items():
        if purpose not in PURPOSES:
            raise ValueError(f"Unknown stage {purpose!r}. Expected one of {PURPOSES}.")
        specs[purpose] = _bind_bare_override(spec, specs[purpose])

    return {p: _backend(specs[p], p, effort) for p in PURPOSES}


def resolve(
    profile: str | None = None,
    *,
    overrides: dict[str, str] | None = None,
    effort: str | None = None,
) -> dict[str, Backend]:
    """Decide which backend serves each stage, for the whole run.

    Called once, early, so a bad spec fails before any file is read or any token spent.
    See `_backends_for` for the spec-resolution rules.
    """
    global _DEFAULT
    backends = _backends_for(profile, overrides=overrides, effort=effort)
    current = _RUN_CONTEXT.get()
    if current is None:
        _ACTIVE.clear()
        _ACTIVE.update(backends)
        _DEFAULT = replace(_DEFAULT, backends=_ACTIVE)
    else:
        _RUN_CONTEXT.set(replace(current, backends=backends))
    return dict(backends)


#: Overlay consulted by `backend_for` before `_ACTIVE` — see `pinned()`. A `ContextVar`
#: rather than a module global: FastAPI runs a sync route in a threadpool with a *copied*
#: context, so a pin set inside one request is invisible to a concurrently running job's
#: own context and to other requests, with no manual save/restore needed.
_PINNED: ContextVar[dict[str, Backend] | None] = ContextVar("_pinned_backends", default=None)


@contextmanager
def pinned(
    profile: str,
    *,
    overrides: dict[str, str] | None = None,
    effort: str | None = None,
) -> Iterator[dict[str, Backend]]:
    """Route every stage through `profile` (plus per-stage `overrides`) for this block only.

    For a one-off web-UI action (e.g. the import wizard's tag-suggestion pass) that must
    not ride on whatever `_ACTIVE` happens to hold — or fall through to `backend_for`'s
    claude default — without repointing a tailoring job that may be mid-run. Unlike
    `resolve()`, never touches `_ACTIVE`.
    """
    backends = _backends_for(profile, overrides=overrides, effort=effort)
    token = _PINNED.set(backends)
    try:
        yield backends
    finally:
        _PINNED.reset(token)


def backend_spec_for(purpose: str) -> str:
    """Serialize one resolved backend as a ``provider:model[@base_url]`` spec string."""
    backend = backend_for(purpose)
    origin = backend.origin or backend.provider
    spec = f"{origin}:{backend.model}"
    if backend.base_url:
        spec += f"@{backend.base_url}"
    return spec


def backend_specs_snapshot() -> dict[str, str]:
    """Snapshot every active stage's spec for persisting with a job directory."""
    return {purpose: backend_spec_for(purpose) for purpose in PURPOSES}


@contextmanager
def pinned_specs(
    specs: dict[str, str],
    *,
    effort: str | None = None,
) -> Iterator[dict[str, Backend]]:
    """Pin exact per-stage specs for one-off calls outside the job runner.

    Used by cover-letter regeneration on a restarted server, where ``_ACTIVE`` is empty
    and ``pinned(profile)`` would mis-route hybrid runs.
    """
    backends = {
        purpose: _backend(
            specs[purpose],
            purpose,
            effort or DEFAULT_EFFORT.get(purpose, "medium"),
        )
        for purpose in specs
    }
    token = _PINNED.set(backends)
    try:
        yield backends
    finally:
        _PINNED.reset(token)


def backend_for(purpose: str) -> Backend:
    """The resolved backend for one stage, defaulting to Claude if `resolve` never ran.

    The default matters: `jd.extract` and `relevance.score_table` are importable library
    functions, and tests and scripts call them without going through the CLI. A `pinned()`
    block, if active in this context, wins over both `_ACTIVE` and that default.
    """
    if purpose not in PURPOSES:
        raise ValueError(f"Unknown stage {purpose!r}. Expected one of {PURPOSES}.")
    override = _PINNED.get()
    if override is not None:
        return override[purpose]
    backends = _current_context().backends
    if not backends:
        resolve("claude")
        backends = _current_context().backends
    return backends[purpose]


def provider_for(purpose: str) -> str:
    return backend_for(purpose).provider


def model_for(purpose: str) -> str:
    return backend_for(purpose).model


def base_url_for(purpose: str) -> str | None:
    return backend_for(purpose).base_url


def effort_for(purpose: str) -> str:
    return backend_for(purpose).effort


def max_token_cap_for(purpose: str) -> int:
    """Ceiling `llm._OpenAICompatClient.request` may escalate a truncated stage up to.

    `LLM_MAX_TOKENS`, if set, pins this (and the starting request — see `max_tokens_for`)
    for every OpenAI-compatible stage, overriding PROVIDER_MAX_TOKENS entirely. Otherwise
    the cap is per-origin: Anthropic's mirrors ANTHROPIC_NONSTREAMING_MAX_TOKENS so the two
    accessors never disagree, Gemini's reflects its real output budget, and every other
    origin (Ollama, LM Studio, plain openai) gets the generic MAX_TOKEN_CAP.
    """
    if _LLM_MAX_TOKENS_ENV is not None:
        return int(_LLM_MAX_TOKENS_ENV)
    origin = backend_for(purpose).origin
    return PROVIDER_MAX_TOKENS.get(origin, MAX_TOKEN_CAP)


def max_tokens_for(purpose: str) -> int:
    """Starting output ceiling for a stage — not necessarily the last one sent.

    Clamped to `max_token_cap_for`, which is what keeps this behaviour-identical to the old
    Anthropic-only clamp: `min(32_000, 21_333)` for Anthropic, `min(32_000, 65_536)` = the
    unclamped 32,000 for everyone else. On the OpenAI-compatible path, a response that
    actually truncates escalates past this up to the same cap — see
    `llm._OpenAICompatClient.request`.
    """
    return min(MAX_TOKENS, max_token_cap_for(purpose))


def structured_mode_for(purpose: str) -> str:
    """How to ask for JSON on the OpenAI-compatible path, for one stage.

    An explicit `LLM_STRUCTURED_MODE` always wins — a user who set it gets it everywhere,
    Gemini included. Left unset, the origin picks: PROVIDER_STRUCTURED_MODE, defaulting to
    the historically-safe "prompt".
    """
    if _STRUCTURED_MODE_ENV is not None:
        return _STRUCTURED_MODE_ENV
    origin = backend_for(purpose).origin
    return PROVIDER_STRUCTURED_MODE.get(origin, "prompt")


#: Env var names `api_key_for` / `credential_gaps` check, in precedence order, keyed by
#: `Backend.origin`. Single source of truth so the two stay in sync. The default arm keeps
#: `lmstudio`/`ollama`/bare-`openai` on the historical `LLM_API_KEY`-then-`OLLAMA_API_KEY`
#: fallback — someone may be proxying LM Studio through a hosted endpoint that wants a key.
_API_KEY_ENV_BY_ORIGIN: dict[str, tuple[str, ...]] = {
    "gemini": ("GEMINI_API_KEY", "GOOGLE_API_KEY", "LLM_API_KEY"),
}
_DEFAULT_API_KEY_ENV = ("LLM_API_KEY", "OLLAMA_API_KEY")


#: Ollama Cloud's own key first: `LLM_API_KEY` may belong to some other custom server and
#: must not be the one sent to ollama.com when both are set.
_OLLAMA_CLOUD_API_KEY_ENV = ("OLLAMA_API_KEY", "LLM_API_KEY")


def api_key_env_for(origin: str, base_url: str | None = None) -> tuple[str, ...]:
    """Which env vars `api_key_for` checks, in order, for a given `Backend.origin`.

    `base_url` only matters for Ollama: pointed at Ollama Cloud, `OLLAMA_API_KEY` wins.
    """
    if origin == "ollama" and is_ollama_cloud(base_url):
        return _OLLAMA_CLOUD_API_KEY_ENV
    return _API_KEY_ENV_BY_ORIGIN.get(origin, _DEFAULT_API_KEY_ENV)


def api_key_for(purpose: str) -> str:
    """Credential for a stage's provider.

    Local and Ollama Cloud endpoints authenticate through the daemon rather than a bearer
    token, so an empty string is a valid answer for most origins — `llm.py` omits the
    header entirely when there is no key, which some servers require. Gemini is the
    exception: `llm.client_for` raises before this is even reached if its key is missing
    (see PROVIDERS_REQUIRING_KEY), so an empty string here would never actually be sent.
    """
    backend = backend_for(purpose)
    if backend.provider == "anthropic":
        return anthropic_api_key()
    for name in api_key_env_for(backend.origin, backend.base_url):
        value = credential(name)
        if value:
            return value
    return ""


def credential_gaps(profile: str, overrides: dict[str, str] | None = None) -> list[str]:
    """Which stages of `profile` would fail for lack of a credential, without resolving it.

    Pure: built on `parse_spec` alone, never calls `resolve`, never touches `_ACTIVE`. That
    matters for the web layer — a request-thread validation call that resolved would
    silently reroute a job that is mid-run, since `_ACTIVE` is process-global. An unknown
    profile is not this function's problem (`resolve` raises `ValueError` for that); it
    just reports no gaps.
    """
    if profile.strip() in MODEL_PROFILES:
        specs = dict(MODEL_PROFILES[profile.strip()])
    else:
        try:
            parse_spec(profile)
        except ValueError:
            return []
        specs = dict.fromkeys(PURPOSES, profile)

    for purpose, spec in (overrides or {}).items():
        if purpose in PURPOSES:
            specs[purpose] = _bind_bare_override(spec, specs.get(purpose, spec))

    gaps: list[str] = []
    seen: set[tuple[str, bool]] = set()
    for spec in specs.values():
        try:
            origin, _model, base_url = parse_spec(spec)
        except ValueError:
            continue
        base_url = base_url or _default_base(origin)
        cloud = origin == "ollama" and is_ollama_cloud(base_url)
        if not requires_key(origin, base_url) or (origin, cloud) in seen:
            continue
        seen.add((origin, cloud))
        env = api_key_env_for(origin, base_url)
        if not any(credential(name) for name in env):
            needed_by = f"Ollama Cloud ({base_url})" if cloud else f"the {origin!r} provider"
            gaps.append(f"{' or '.join(env)} is not set — required by {needed_by}.")
    return gaps


def fingerprint(purpose: str) -> str:
    """Identity of the backend serving a stage, for cache keys.

    Folded into `jd._slug` and `relevance._score_cache_path`. Without it, switching models
    and re-running silently serves the *previous* model's output — the same class of bug
    `_PROMPT_VERSION` exists to prevent, and one that would make any A/B between backends
    meaningless. Keyed on `origin or provider`, not `provider` alone: after `_backend`'s
    remap, Ollama, LM Studio, and Gemini all share `provider == "openai"`, so two backends
    with the same model string but different origins would otherwise collide.
    """
    backend = backend_for(purpose)
    value = f"{backend.origin or backend.provider}|{backend.model}|{backend.effort}"
    guidance = active_guidance()
    if guidance is not None and purpose in (
        "extract", "score", "facets", "rewrite", "expand", "skills", "cover"
    ):
        value += "|guidance:" + guidance.fingerprint()
    return value


# --------------------------------------------------------------------------------------
# PDF rendering backend
# --------------------------------------------------------------------------------------
#
# The fit loop decides overflow on a real page count, which means something has to turn a
# .docx into a PDF. Word via COM does it best and runs only on Windows; LibreOffice
# headless does it anywhere, which is what makes the container possible.
#
# These are not interchangeable to the character: two engines lay text out slightly
# differently, so each carries its own calibration (see below). Switching backend without
# switching constants is the failure this pairing exists to prevent.

PDF_BACKENDS = ("word", "soffice")


def _default_pdf_backend() -> str:
    """Pick a converter for this machine: Word on Windows, LibreOffice elsewhere.

    Overridable with RESUME_TAILOR_PDF_BACKEND, which is how a Windows developer can test
    the container's engine without a container.
    """
    requested = os.environ.get("RESUME_TAILOR_PDF_BACKEND", "auto").strip().lower()
    if requested in PDF_BACKENDS:
        return requested
    if requested not in ("auto", ""):
        raise ValueError(
            f"RESUME_TAILOR_PDF_BACKEND must be one of {PDF_BACKENDS} or 'auto', "
            f"got {requested!r}"
        )
    return "word" if platform.system() == "Windows" else "soffice"


def _default_soffice_binary() -> str:
    """Find the LibreOffice executable: env var, PATH, or standard OS install paths."""
    if env_val := os.environ.get("SOFFICE_BINARY"):
        return env_val
    if found := (shutil.which("soffice") or shutil.which("libreoffice")):
        return found
    if platform.system() == "Darwin":
        for mac_path in (
            Path("/Applications/LibreOffice.app/Contents/MacOS/soffice"),
            Path.home() / "Applications/LibreOffice.app/Contents/MacOS/soffice",
        ):
            if mac_path.is_file() and os.access(mac_path, os.X_OK):
                return str(mac_path)
    elif platform.system() == "Windows":
        for win_path in (
            Path(r"C:\Program Files\LibreOffice\program\soffice.exe"),
            Path(r"C:\Program Files (x86)\LibreOffice\program\soffice.exe"),
        ):
            if win_path.is_file():
                return str(win_path)
    return "soffice"


PDF_BACKEND = _default_pdf_backend()

#: How to invoke LibreOffice. Uses SOFFICE_BINARY env var, PATH lookup, standard
#: macOS / Windows install locations, or falls back to "soffice".
SOFFICE_BINARY = _default_soffice_binary()

#: Seconds allowed for one LibreOffice conversion. A cold start costs a couple of seconds;
#: this only exists so a wedged process fails the run instead of hanging it forever.
SOFFICE_TIMEOUT = float(os.environ.get("SOFFICE_TIMEOUT", "120"))


# --------------------------------------------------------------------------------------
# Page fitting
# --------------------------------------------------------------------------------------

DEFAULT_PAGE_TARGET = 1

#: Overflow ladder limits (see `fit.fit`). Combine and pull-back each run once per bullet
#: set; whole-bullet drops are deterministic and cost only a render, so they get a few
#: rounds. Exhausting them is an error, never a silent truncation.
MAX_DROP_ROUNDS = 3

#: Rounds of the fit loop's top-up (`fit.top_up`): once the loop settles on an underfull
#: page it cannot grow, each round re-adds bullets the caps allow, then tries one bullet
#: past the per-entry cap, then a new entry, rewriting only the added bullets. Every
#: round's added bullets get a measured widow pass; a second round runs only when that
#: pass freed lines again.
MAX_TOPUP_ROUNDS = 2

#: A multi-line bullet is a pull-back candidate when its final line is at most this
#: fraction full. Wider than `WIDOW_MIN_FILL`: a bullet at 35% is not a widow, but a
#: one-line cut still frees its whole last line.
PULLBACK_MAX_FILL = 0.40

#: Where `scripts/calibrate.py` writes its measurements, one file per PDF backend.

#: Word-measured values for the current template, used when no calibration file exists.
#: Kept in source so a fresh checkout behaves exactly as it did before calibration became
#: data, and so the Windows path needs no generated file at all.
_FALLBACK_CHARS_PER_LINE = 101
_FALLBACK_LINES_PER_PAGE = 52

#: Plausibility band for a *loaded* calibration file. `calibrate.py` has its own,
#: independent collapsed-search guard that stops a bad measurement from ever being
#: written — this is the second, cheaper line of defense for a file that reached disk
#: anyway (hand-edited, copied from a different template, or written before that guard
#: existed). A `chars_per_line=20` file measured exactly this way once: it silently
#: capped every rewritten bullet at ~15-35 characters for two days before anyone noticed.
PLAUSIBLE_CHARS_PER_LINE = (40, 200)
PLAUSIBLE_LINES_PER_PAGE = (25, 90)


def _load_calibration(
    backend: str, directory: Path | None = None, *, paths: dict[str, Path] | None = None
) -> tuple[int, int, str, str | None]:
    """Read measured fit constants for `backend`, falling back to the Word-derived pair.

    Returns `(chars_per_line, lines_per_page, source, rejection)`. `source` names the
    file used, or is literally `"fallback"` when using the built-in constants — checked
    by exact string equality elsewhere (`template_ops.py`, the frontend), so its two
    possible shapes ("fallback" / a path) must never change. `rejection` is `None`
    unless a file existed but its numbers fell outside `PLAUSIBLE_CHARS_PER_LINE`/
    `PLAUSIBLE_LINES_PER_PAGE`, in which case it names what was rejected and why —
    additional detail layered on top of `source == "fallback"`, not a new source shape.
    The source is reported rather than swallowed because inheriting Word's constants
    under LibreOffice is a silent way to mis-size every page — `report.py` and the web
    UI both surface it.
    """
    path = (directory or sys.modules[__name__].CALIBRATION_DIR) / f"{backend}.json"
    if not path.exists():
        return _FALLBACK_CHARS_PER_LINE, _FALLBACK_LINES_PER_PAGE, "fallback", None
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
        chars_per_line = int(raw["chars_per_line"])
        lines_per_page = int(raw["lines_per_page"])
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise ValueError(
            f"{path} is not a usable calibration file ({exc}). Delete it to fall back to "
            f"the built-in constants, or regenerate it with scripts/calibrate.py."
        ) from exc

    chars_lo, chars_hi = PLAUSIBLE_CHARS_PER_LINE
    if raw.get("input_digest"):
        from resume_tailor.document.calibration_cache import input_digest

        if raw["input_digest"] != input_digest(paths=paths, backend=backend):
            return (
                _FALLBACK_CHARS_PER_LINE, _FALLBACK_LINES_PER_PAGE, "fallback",
                "Page fit needs tuning for the current template and resume.",
            )
    lines_lo, lines_hi = PLAUSIBLE_LINES_PER_PAGE
    if not (chars_lo <= chars_per_line <= chars_hi) or not (lines_lo <= lines_per_page <= lines_hi):
        # A bad file must not brick the app — fall back rather than raise, but name
        # what was rejected so the cause (not just the symptom) is visible wherever
        # CALIBRATION_SOURCE/CALIBRATION_REJECTION are surfaced.
        rejection = (
            f"{path} was rejected: chars_per_line={chars_per_line}, "
            f"lines_per_page={lines_per_page} (plausible ranges are "
            f"{PLAUSIBLE_CHARS_PER_LINE} and {PLAUSIBLE_LINES_PER_PAGE}). Using built-in "
            "constants instead — delete this file and re-run scripts/calibrate.py."
        )
        return _FALLBACK_CHARS_PER_LINE, _FALLBACK_LINES_PER_PAGE, "fallback", rejection
    return chars_per_line, lines_per_page, str(path), None


#: Calibration constants, measured by `scripts/calibrate.py` against the real template and
#: the active PDF backend. Re-run that script after any change to fonts, margins, the
#: template, or the converter — these numbers describe one engine rendering one document.
_PATH_NAMES = (
    "DATA_DIR", "TEMPLATES_DIR", "OUTPUT_DIR", "CACHE_DIR", "CALIBRATION_DIR",
    "MASTER_RESUME_PATH", "SETTINGS_PATH", "SOURCE_STATUS_PATH", "LIBRARIES_PATH",
    "APPLICATIONS_PATH",
    "APPLICANT_PROFILE_PATH", "APPLICATIONS_OUTPUT_DIR", "DEFAULT_TEMPLATE_PATH",
    "BASELINE_TEMPLATE_PATH", "TEMPLATE_PROFILE_PATH", "TEMPLATE_LIBRARY_DIR",
    "COVER_TEMPLATE_PATH", "COVER_TEMPLATE_META_PATH",
)
_CALIBRATION_NAMES = (
    "CHARS_PER_LINE", "LINES_PER_PAGE", "CALIBRATION_SOURCE", "CALIBRATION_REJECTION",
)


@dataclass(frozen=True)
class RunContext:
    """Workspace-specific values captured for one in-process run."""

    workspace_id: str | None
    paths: dict[str, Path]
    backends: dict[str, Backend]
    calibration: tuple[int, int, str, str | None]
    tag_aliases: dict[str, str] | None = None
    verb_families: dict[str, tuple[str, ...]] | None = None
    styles: dict[str, str | None] | None = None
    guidance: GuidanceSnapshot | None = None


def _legacy_paths() -> dict[str, Path]:
    data, templates, output, cache = DATA_ROOT, TEMPLATES_ROOT, OUTPUT_ROOT, CACHE_ROOT
    return {
        "DATA_DIR": data, "TEMPLATES_DIR": templates, "OUTPUT_DIR": output,
        "CACHE_DIR": cache,
        "CALIBRATION_DIR": _dir_from_env("RESUME_TAILOR_CALIBRATION_DIR", data / "calibration"),
        "MASTER_RESUME_PATH": data / "master_resume.json",
        "SETTINGS_PATH": data / "settings.json",
        "SOURCE_STATUS_PATH": data / "source_status.json",
        "LIBRARIES_PATH": data / "libraries.json",
        "APPLICATIONS_PATH": data / "applications.json",
        "APPLICANT_PROFILE_PATH": data / "applicant_profile.json",
        "APPLICATIONS_OUTPUT_DIR": output / "applications",
        "DEFAULT_TEMPLATE_PATH": templates / "main_template.docx",
        "BASELINE_TEMPLATE_PATH": templates / "original_export.docx",
        "TEMPLATE_PROFILE_PATH": templates / "template_profile.json",
        "TEMPLATE_LIBRARY_DIR": templates / "library",
        "COVER_TEMPLATE_PATH": templates / "cover_template.docx",
        "COVER_TEMPLATE_META_PATH": templates / "cover_template.meta.json",
    }


_INITIAL_PATHS = _legacy_paths()
_DEFAULT = RunContext(
    None, _INITIAL_PATHS, _ACTIVE,
    _load_calibration(PDF_BACKEND, _INITIAL_PATHS["CALIBRATION_DIR"], paths=_INITIAL_PATHS),
    dict(library_seeds.BUILTIN_PACKS["core-tech"]["tag_aliases"]),
    dict(library_seeds.BUILTIN_PACKS["core-tech"]["verb_families"]),
)
_RUN_CONTEXT: ContextVar[RunContext | None] = ContextVar("run_context", default=None)


def _current_context() -> RunContext:
    return _RUN_CONTEXT.get() or _DEFAULT


def __getattr__(name: str) -> Any:
    context = _current_context()
    if name in _PATH_NAMES:
        return context.paths[name]
    if name in _CALIBRATION_NAMES:
        return context.calibration[_CALIBRATION_NAMES.index(name)]
    if name == "_ACTIVE_WORKSPACE_ID":
        return context.workspace_id
    if name == "TAG_ALIASES":
        return context.tag_aliases
    if name == "VERB_FAMILIES":
        return context.verb_families
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


@contextmanager
def use_context(context: RunContext) -> Iterator[RunContext]:
    token = _RUN_CONTEXT.set(context)
    try:
        yield context
    finally:
        _RUN_CONTEXT.reset(token)


def context_for_workspace(workspace_id: str) -> RunContext:
    paths = workspace_paths(workspace_id)
    calibration = _load_calibration(PDF_BACKEND, paths["CALIBRATION_DIR"], paths=paths)
    from .content import libraries

    effective = libraries.resolve_effective(workspace_id)
    return RunContext(
        workspace_id, paths, {}, calibration,
        dict(effective.tag_aliases), dict(effective.verb_families),
        {"rewrite": None, "expand": None, "cover": None},
    )


def default_context() -> RunContext:
    """Snapshot the process default for a legacy job with no workspace id."""
    return replace(
        _DEFAULT,
        paths=dict(_DEFAULT.paths),
        backends=dict(_DEFAULT.backends),
        tag_aliases=dict(_DEFAULT.tag_aliases or {}),
        verb_families=dict(_DEFAULT.verb_families or {}),
        styles=(
            dict(_DEFAULT.styles) if _DEFAULT.styles is not None
            else {"rewrite": None, "expand": None, "cover": None}
        ),
    )


def set_vocabulary(
    aliases: dict[str, str], families: dict[str, tuple[str, ...]]
) -> None:
    """Install vocabulary for the current run, or the process default."""
    global _DEFAULT
    current = _RUN_CONTEXT.get()
    updated = replace(current or _DEFAULT, tag_aliases=aliases, verb_families=families)
    if current is None:
        _DEFAULT = updated
    else:
        _RUN_CONTEXT.set(updated)


def set_styles(styles: dict[str, str | None]) -> bool:
    """Bind styles to an active run; return False outside a run context."""
    current = _RUN_CONTEXT.get()
    if current is None:
        return False
    _RUN_CONTEXT.set(replace(current, styles=styles))
    return True


def active_guidance() -> GuidanceSnapshot | None:
    """Frozen profile guidance for this run, or None for the legacy path."""
    return _current_context().guidance


def set_guidance(guidance: GuidanceSnapshot | None) -> None:
    global _DEFAULT
    current = _RUN_CONTEXT.get()
    updated = replace(current or _DEFAULT, guidance=guidance)
    if current is None:
        _DEFAULT = updated
    else:
        _RUN_CONTEXT.set(updated)


def active_styles() -> dict[str, str | None] | None:
    current = _RUN_CONTEXT.get()
    return current.styles if current is not None else None


def run_in_context[T](fn: Callable[..., T]) -> Callable[..., T]:
    """Capture this context for a later call, including from another thread."""
    context = copy_context()
    def wrapped(*args: Any, **kwargs: Any) -> T:
        return context.copy().run(fn, *args, **kwargs)
    return wrapped


def submit_in_context[T](executor: Executor, fn: Callable[..., T], *args: Any) -> Future[T]:
    return executor.submit(run_in_context(fn), *args)


def reload_calibration() -> tuple[int, int, str, str | None]:
    """Re-read fit constants into the current run or process default.

    Needed after a web-triggered calibrate so the running process picks up new values
    without a server restart. Returns the same 4-tuple as `_load_calibration`.
    """
    global _DEFAULT
    current = _RUN_CONTEXT.get()
    calibration = _load_calibration(PDF_BACKEND)
    if current is None:
        _DEFAULT = replace(_DEFAULT, calibration=calibration)
    else:
        _RUN_CONTEXT.set(replace(current, calibration=calibration))
    return calibration

#: Below this fraction of the target page's capacity, a page reads as half-empty and the
#: fit loop restores bullets rather than accepting the result.
#:
#: Raised from 0.85 once widow repair landed. The old value was calibrated against pages
#: that still contained widows, so several of the "full" lines it was counting held a
#: single word. With those gone a measured line is a line of real content.
#:
#: This is the one knob here with a running cost, and it was measured rather than guessed.
#: Same posting, same everything else:
#:
#:   0.93 -> grow until ≥93% fill (target density for one-pagers)
#:   0.92 -> 13 of 15 bullets, 49/52 lines, 3 iterations
#:   0.88 -> 12 of 15 bullets, 47/52 lines, 2 iterations
#:   0.86 -> accepts ~86% fill on first measure; fewer grow rounds when the estimate
#:         undershoots the real render (common after rewrite shortens bullets).
#:
#: One extra rewrite call buys one extra bullet. Lower = fewer API rounds, more
#: whitespace; raise toward 0.93 for a denser page (more grow/rewrite rounds).
UNDERFLOW_THRESHOLD = 0.93

#: Measured lines a page may sit under `ceil(fill target × capacity)` and still count as
#: full — no grow round, no top-up, no "only N% full" warning. Live runs hit 54/54 on the
#: first draft, lost one line to widow repair (53, 91% vs 93%), then spent four LLM calls
#: and four Word renders on top-ups that overflowed and were reverted to close that line.
FILL_TOLERANCE_LINES = 1

#: Extra estimated lines past page capacity that `fit_selection._initial_selection_size` may claim.
#:
#: The first rewrite usually lands under the advertised max, so a small optimism margin
#: packs the opening call denser (e.g. 13/15 instead of 12/15) and avoids a grow round.
#: Raise if first renders are still sparse; lower if overflow/shorten thrashing is common.
INITIAL_SELECTION_OVERSHOOT = 2

#: Fraction of the chosen entries' bullets the *first* selection may claim.
#:
#: 1.0 leaves `fit_selection._initial_selection_size` exactly as it was: the binary search's only
#: bound is what the line estimate says fits (typically 14 of 15). Lowering it caps that
#: search — a ceiling, never a floor, and never below one bullet per entry.
#:
#: This bounds the first draft only. The grow loop still restores toward the full pool
#: when a measured page is under `UNDERFLOW_THRESHOLD`, so on its own a low value mostly
#: trades extra rewrite rounds for the same final page. Lower `UNDERFLOW_THRESHOLD`
#: alongside it to actually end on a sparser page.
#:
#: Distinct from `EXPERIENCE_BULLET_SHARE` (selection scoring block, below): this one
#: bounds the total count; that one has no opinion on the count and instead bounds how it
#: splits between experience and projects.
INITIAL_BULLET_SHARE = 1.0

# --------------------------------------------------------------------------------------
# Bullet merging (non-regressive, deterministic proposal)
# --------------------------------------------------------------------------------------
#
# Merging combines multiple selected bullet points within a single entry into fewer
# bullets. It is designed as a space lever that must still preserve correctness
# invariants enforced in `fabrication.check_fabrication`.

#: Affinity threshold schedule for merge proposals.
#: Lower thresholds propose more merges as the fit loop escalates on overflow.
MERGE_AFFINITY_SCHEDULE = (0.55, 0.45, 0.35)

#: Weakest-member relevance score gate used by merge proposals.
#:
#: When at least one bullet in a candidate group is weak, merging is allowed even when
#: overall affinity is not yet extremely high. This encodes the "three mediocre
#: bullets become two better ones" idea.
MERGE_WEAK_SCORE = 4.0

#: How much larger the candidate group's source length may be than the merged
#: bullet's hard maximum.
#:
#: The merge output must fit within the same hard `max` constraints used by rewrite.
#: Since the model must compress multiple bullets into one, we only propose merging
#: when the total source text is not more than ~1.8x the hard max. This bounds how
#: much information the merge is allowed to drop.
MERGE_SOURCE_RATIO = 1.8

#: Maximum merge-group size on the first (most conservative) pass.
#:
#: The merge proposal step allows one extra member on later overflow rungs; the
#: feature stays controlled by these caps plus `MAX_MERGES_PER_RUN`.
MAX_MERGE_GROUP_SIZE = 2

#: Maximum number of merge groups the proposal step may select in one fit iteration.
MAX_MERGES_PER_RUN = 3

#: How many times the fit loop may grow the selection to fill an underfull page. Unlike
#: overflow, exhausting this is not an error: a slightly sparse resume is still valid
#: output, so the loop returns the fullest version it reached. The bound exists because
#: each growth costs an API call and a Word render.
MAX_GROW_ATTEMPTS = 4


# --------------------------------------------------------------------------------------
# Opening-verb variety
# --------------------------------------------------------------------------------------
#
# A resume whose bullets all open "Designed... Engineered... Architected..." reads as one
# note held too long, and the exact-duplicate case ("Designed" twice) reads as an editing
# mistake. Detecting the second is trivial; detecting the first needs to know that those
# three verbs make the same claim, which is what these families encode.
#
# Membership is deliberately conservative. Only verbs listed here participate in
# family-level collisions, so an opener the table has never seen can never be flagged
# wrongly — the cost of an omission is a missed catch, never a false one.

#: Near-synonymous bullet openers, grouped by the claim they make. Past tense, because
#: that is the register `rewrite_prompts._SYSTEM` asks for. Initialised from the built-in
#: `core-tech` pack (`library_seeds.py`) and reassigned wholesale by
#: `libraries.apply_to_config()` once a workspace has its own pack selection — never
#: mutated in place, since `verb_family`'s index cache below keys on object identity.

#: How many bullets may open with verbs from the same family before it reads repetitive.
#: Two is the point where a pattern becomes visible but is still plausibly incidental; a
#: third makes the whole resume sound like one sentence.
MAX_SAME_FAMILY_OPENERS = 2
#: A longer page earns one more same-family opener per this many bullets. A technical
#: page of 15 bullets routinely carries four build-family openers (built, developed,
#: implemented, designed); capping that at two flagged 2-3 bullets on ~95% of runs and
#: pushed the repair toward weaker unlisted verbs ("Coded", "Programmed").
BULLETS_PER_FAMILY_OPENER = 5

#: Openers that name no action or no ownership ("Assisted…", "Helped…", "Responsible
#: for…"). `bullet_checks.verb_collisions` flags them like a repeated opener, so the same
#: bounded verb repair re-voices them. Deliberately short and unambiguous: a verb that is
#: strong in some trades ("Performed due diligence", "Served 200 clients") stays out, and
#: `libraries.py` packs never extend it — the repair swaps the verb, never the claim.
WEAK_OPENERS = frozenset({
    "assisted", "aided", "helped", "handled", "worked", "participated", "responsible",
    "involved", "tasked", "utilized", "utilised", "used", "attended",
})


def family_opener_cap(bullet_count: int) -> int:
    """Same-family openers allowed across `bullet_count` bullets (exact repeats never are)."""
    return max(MAX_SAME_FAMILY_OPENERS, math.ceil(bullet_count / BULLETS_PER_FAMILY_OPENER))


def _build_verb_index(families: dict[str, tuple[str, ...]]) -> dict[str, str]:
    """Invert `families` into {verb: family}, first-wins on a verb listed twice.

    A verb in two families is expected once families come from separately-authored
    packs — "administered" is legitimately both core-tech's `operate` and a nursing
    pack's `care`. Composing packs is `libraries.py`'s job (it resolves the collision by
    pack order and reports it as a diagnostic); this function stays total so a
    hand-edited or partially-composed table can never crash an entrypoint. Duplicate
    detection *within one pack* is a save-time validation rule instead, in
    `libraries.validate_pack`.
    """
    index: dict[str, str] = {}
    for family, verbs in families.items():
        for verb in verbs:
            index.setdefault(verb, family)
    return index


#: Lazily (re)built cache of `_build_verb_index(VERB_FAMILIES)`, invalidated whenever
#: `VERB_FAMILIES` is reassigned to a new object — `libraries.apply_to_config()` and
#: `monkeypatch.setattr(config, "VERB_FAMILIES", ...)` both work this way, so neither
#: needs to know this cache exists. Compared by identity (`is not`), not equality: two
#: equal-but-distinct dicts must still invalidate, since equality on a multi-thousand
#: entry table would cost more than just rebuilding it.
_VERB_INDEX: dict[str, str] | None = None
_VERB_INDEX_SOURCE: object | None = None
_VERB_INDEX_LOCK = threading.Lock()


def verb_family(word: str) -> str | None:
    """The family `word` belongs to, or None if it is not a known opener.

    Case-insensitive, and tolerant of the trailing punctuation a one-word opener never
    has but a caller might pass in.
    """
    global _VERB_INDEX, _VERB_INDEX_SOURCE
    families = sys.modules[__name__].VERB_FAMILIES
    with _VERB_INDEX_LOCK:
        if _VERB_INDEX is None or _VERB_INDEX_SOURCE is not families:
            _VERB_INDEX = _build_verb_index(families)
            _VERB_INDEX_SOURCE = families
        index = _VERB_INDEX
    return index.get(word.strip().strip(".,;:").lower())


def family_verbs(family: str) -> tuple[str, ...]:
    """Every known opener in `family`, for suggesting alternatives to the model."""
    return sys.modules[__name__].VERB_FAMILIES.get(family, ())


# --------------------------------------------------------------------------------------
# Line occupancy
# --------------------------------------------------------------------------------------
#
# The character budget is a cliff, not a slope: a bullet two characters past a line
# boundary wraps onto a whole extra line that holds one word. Measured across every render
# in output/, every widowed bullet came back at 204-207 characters against a 202-character
# budget, while the two clean runs had every bullet at 180-199. Two characters per bullet
# was the entire difference.
#
# These live here rather than in fit.py because rewrite.py needs them too, and fit.py
# already imports rewrite — defining them there would invert that dependency.


def slugify(label: str) -> str:
    """Lowercase, hyphenated, filesystem/id-friendly form of `label`.

    Shared so `workspace.new_workspace_id` and `data.Experience`'s auto-filled id use the
    same rule — two independent slug functions would drift the moment either one's edge
    cases (accents, leading digits, empty input) were fixed only in one place.
    """
    return re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")[:40]


def line_span(text: str) -> int:
    """How many rendered lines `text` occupies, by the character budget."""
    return max(1, math.ceil(len(text) / sys.modules[__name__].CHARS_PER_LINE))


def last_line_fill(text: str) -> int:
    """How many characters land on `text`'s final rendered line.

    A length that is an exact multiple of `CHARS_PER_LINE` fills its last line completely,
    so it returns `CHARS_PER_LINE` rather than 0 — that case is the ideal, not a widow.
    """
    width = sys.modules[__name__].CHARS_PER_LINE
    remainder = len(text) % width
    return remainder or min(len(text), width)


def skill_group_line(label: str, items: list[str]) -> str:
    """The text one skills group renders as, for line-budget estimation.

    Shared so `fit_lines._fixed_overhead_lines` and `facets_resolve._resolve_skill_group`
    cannot drift: one measures the overhead, the other must not grow it. Mirrors the join in
    `render.build_context`'s skills block. The ": " separator is hardcoded here rather
    than read from `template_profile.SkillsMapping.separator`; if that ever needs
    honouring, this is the one place it lands.
    """
    return f"{label}: {', '.join(items)}"


#: Measured PDF lines below half width are repair candidates. The character estimate is
#: deliberately more conservative because it disagrees with real layout around wraps.
WIDOW_MIN_FILL = 0.50
WIDOW_EST_FILL = 0.30
#: Below this fill, save a line. Moderately short lines may grow from their own source.
WIDOW_SHORTEN_MAX = 0.35
#: Last-line fill an EXTEND repair aims for at minimum. Just above `WIDOW_MIN_FILL` (the
#: margin is about `WIDOW_SAFETY` characters) so the window stays wide enough for a model
#: to land in; aiming at 80% left only ~15 characters and most drafts missed it.
WIDOW_EXTEND_FILL = 0.55

#: Characters of headroom held back from a line boundary when setting a ceiling. The
#: observed overshoot was 2-5 characters, so a ceiling placed exactly on the boundary would
#: simply be crossed again.
WIDOW_SAFETY = 5


# --------------------------------------------------------------------------------------
# Tag normalisation
# --------------------------------------------------------------------------------------

#: Maps the many ways a JD might name a skill onto the canonical tag used in
#: master_resume.json. Keys and values are lowercase. Initialised from the built-in
#: `core-tech` pack (`library_seeds.py`) and reassigned wholesale by
#: `libraries.apply_to_config()` once a workspace has its own pack selection — extend
#: via a pack, not by hand-editing this dict; an unmatched alias costs a missed bullet,
#: never a crash.


def canonical_tag(raw: str) -> str:
    """Normalise a skill name to the canonical tag form used across the project."""
    cleaned = raw.strip().lower()
    return sys.modules[__name__].TAG_ALIASES.get(cleaned, cleaned)


def tag_alias_fingerprint() -> str:
    """Digest of `TAG_ALIASES`, for folding into `jd._slug`.

    `jd.extract` re-canonicalises every keyword through this table after the model
    responds (`jd.py`, right before the cache write), but the cache key itself never
    covered the table — so editing an alias silently changes what a cached extraction
    would produce today while every already-cached `.requirements.json` keeps serving
    the pre-edit mapping. That is the exact failure `config.fingerprint()` exists to
    prevent for the backend/model/effort triple; this closes the same hole for the one
    remaining input `_slug` was missing.
    """
    aliases = sys.modules[__name__].TAG_ALIASES
    payload = "\n".join(f"{k}={v}" for k, v in sorted(aliases.items()))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]


# --------------------------------------------------------------------------------------
# Selection scoring
# --------------------------------------------------------------------------------------

#: Weight applied to a bullet matching a JD "must have" keyword vs a "nice to have".
MUST_HAVE_WEIGHT = 3.0
NICE_TO_HAVE_WEIGHT = 1.0

#: Weight for a *soft-skill* must-have ("communication", "teamwork", "leadership") in place
#: of MUST_HAVE_WEIGHT. Lower deliberately: soft tags are broad and sit on almost every
#: entry, including the volunteer and support roles, so at full weight a posting naming
#: three of them as required could float a non-technical entry over a relevant job. Measured
#: on a data-operations posting: once soft skills actually matched tags, an office-assistant
#: entry went from 0.0 to 7.0 while the current internship sat at 12.5.
#:
#: Only `must_have` is split this way. `nice_to_have` stays at NICE_TO_HAVE_WEIGHT for both
#: kinds — at 1.0 the distortion never showed up, and a second knob with no failure behind
#: it is one more thing to keep calibrated.
SOFT_SKILL_WEIGHT = 1.5

#: Tags that also evidence a soft-skill must-have whose canonical is the key, at the same
#: SOFT_SKILL_WEIGHT. Extraction canonicalises "multi-disciplinary teams" or "pair
#: programming" to `teamwork`, but a bullet showing it ("Led a 3-person team",
#: "Mentored students") is tagged `leadership` or `mentorship` and scored zero for it, so
#: the people-facing bullets resume scanners grade lost every ranking. One soft keyword
#: still counts once per bullet however many of these tags it carries.
SOFT_SKILL_RELATED_TAGS: dict[str, frozenset[str]] = {
    "teamwork": frozenset({
        "collaboration", "leadership", "project management", "stakeholder management",
    }),
    "leadership": frozenset({
        "mentorship", "project management", "teaching", "training",
    }),
    "communication": frozenset({
        "documentation", "mentorship", "presentation", "teaching", "technical writing",
        "training",
    }),
}

#: Multiplier on the LLM relevance score (0-10 per bullet) from `relevance.score_table`, which
#: is *added* to the keyword score rather than replacing it. The two signals answer different
#: questions: tag overlap asks "did they literally use this tool", the semantic score asks
#: "is this bullet relevant to this role at all" — the latter is the only one that can see
#: domain resonance a tag cannot encode (an academic-advising project against a posting about
#: academic content partnerships).
#:
#: At 0.5 a perfect 10/10 contributes 5.0, comparable to a technical must-have, so neither
#: signal can silently dominate. **At 0.0 scoring is byte-identical to keyword-only**, which
#: is what makes the semantic layer A/B-testable: run the same posting at 0.0 and 0.5 and
#: diff the report rather than guessing which change moved the ranking.
SEMANTIC_WEIGHT = 0.5

#: Small nudge toward bullets carrying a concrete metric, which read stronger at equal
#: keyword relevance.
METRIC_BONUS = 0.5

#: Coverage-aware bullet selection (`selection._take_ranked`): a posting keyword already
#: shown on the page is worth less to the next bullet, so a must-have proven once can
#: lose its slot to one not yet shown. Off by default until `scripts/eval_selection.py`
#: shows it raises must-have coverage on real runs; `RESUME_TAILOR_COVERAGE_SELECTION=1`
#: turns it on.
COVERAGE_SELECTION = os.environ.get("RESUME_TAILOR_COVERAGE_SELECTION", "") == "1"
#: Keyword weight multiplier by how many selected bullets already show that keyword:
#: full for the first, this for the second, nothing after that.
COVERAGE_REPEAT_DISCOUNT = 0.5

#: Mild preference for recent work, applied in code at every ranking site (entry choice,
#: bullet selection, the fit loop's drop / pull-back / top-up order) and never sent to the
#: model, so the cached score table is unaffected. An entry's score is multiplied by
#: `1 + RECENCY_WEIGHT * 0.5 ** (age_months / RECENCY_HALF_LIFE_MONTHS)`, with age taken
#: from the entry's end date ("Present" is age 0; no parseable date is neutral, 1.0). At
#: 0.20 a clearly more relevant older entry still wins; recency settles near-ties. 0.0
#: restores relevance-only ranking.
RECENCY_WEIGHT = 0.20
RECENCY_HALF_LIFE_MONTHS = 24

#: Pins "today" for the recency weight (``YYYY-MM``); ``None`` uses the real date. Tests
#: pin it so rankings never drift with the calendar.
RECENCY_TODAY: str | None = None

#: How many entries each section may show. Experience and projects are ranked separately
#: against these caps, so a job only ever competes with other jobs — pooling them let side
#: projects push out the current employer.
#:
#: These are a shape decision, not a fitting one: the fit loop trims *bullets* within the
#: chosen entries and never drops an entry to save space.
MAX_EXPERIENCE_ENTRIES = 3
MAX_PROJECT_ENTRIES = 2

#: Titles used when `data.MasterResume` migrates a legacy (pre-`sections`) file into the
#: four default sections, and when the editor creates a new section of one of these kinds
#: with no title of its own yet.
DEFAULT_SECTION_TITLES: dict[str, str] = {
    "education": "Education",
    "experience": "Experience",
    "projects": "Projects",
    "skills": "Skills",
}

#: Which `template_profile.TemplateProfile.enabled` key gates each `data.Section.kind`,
#: and whether that kind renders when the key is absent from an older or hand-built
#: layout dict. `render.build_context`'s `sections` list and `fit.fit`'s
#: missing-prototype warning both key off this so the two can never disagree about what
#: "enabled" means for a kind. Not the kind string itself for `project`/`list` — `enabled`'s
#: keys predate `Section.kind` and use the legacy plural/suffixed names (`"projects"`,
#: `"list_section"`).
SECTION_KIND_ENABLED_KEY: dict[str, str] = {
    "experience": "experience",
    "project": "projects",
    "list": "list_section",
    "education": "education",
    "skills": "skills",
}
#: `list_section` defaults closed — no template has ever had this prototype before
#: generic mode existed; the other four default open, matching pre-existing behaviour.
SECTION_KIND_ENABLED_DEFAULT: dict[str, bool] = {
    "experience": True,
    "project": True,
    "list": False,
    "education": True,
    "skills": True,
}

#: Overall experience-vs-projects split of the bullets `selection.select_within_entries`
#: chooses, as a fraction going to experience (e.g. 0.65 -> 65% experience / 35% projects).
#: `None` is the original behaviour: one flat pool ranked purely by `score`, which lets a
#: keyword-dense project out-rank every job for the shared discretionary budget. Distinct
#: from `INITIAL_BULLET_SHARE` (page-fitting block, above), which bounds the *first
#: draft's total bullet count* and has no opinion on how that count splits between
#: sections.
EXPERIENCE_BULLET_SHARE: float | None = None

#: Ceiling on how many bullets any single job or project may take, applied inside whichever
#: pool (flat, or per-section under `EXPERIENCE_BULLET_SHARE`) is in play. `None` is
#: uncapped — the original behaviour, where a single rich entry could take as many lines as
#: the ranking gave it. `selection.selectable_total` is what the fit loop's grow condition
#: must compare against once this is set, since the pool saturates below the raw bullet
#: count and comparing against the raw count would spin the grow loop for nothing.
MAX_BULLETS_PER_ENTRY: int | None = None

#: Cap on tech tags rendered in one project header line. The facets stage may propose
#: more; code truncates to this after applying the character budget.
MAX_PROJECT_TECH = 4

#: Soft ceiling on the "Relevant Coursework: …" bullet, in rendered lines. The facets
#: stage picks courses best-first; code keeps only as many as fit under this span.
COURSEWORK_MAX_LINES = 2

#: Characters reserved when a calibration file has no measured `header_chars_per_line`
#: (`project_header_chars`). `CHARS_PER_LINE` is measured on lowercase bullet prose; a
#: header has a bold name, capitals and a right-aligned date, so it holds fewer
#: characters. 13 is the observed cutoff across 390 Word-rendered headers (121-char
#: body lines wrapped every header of 109+ characters and none of 108 or fewer).
PROJECT_HEADER_GAP = 13

#: Plausibility band for a measured `header_chars_per_line`, same role as
#: `PLAUSIBLE_CHARS_PER_LINE`.
PLAUSIBLE_HEADER_CHARS = (40, 200)


def project_header_chars() -> int:
    """Characters one project header line holds: `name | tech | link` plus its date.

    Read from the active calibration file's optional `header_chars_per_line` (measured
    by `calibrate.calibrate_header_chars`), else `CHARS_PER_LINE - PROJECT_HEADER_GAP`.
    Only a first estimate — `fit_shrink.header_pass` checks the rendered PDF and trims
    tech tags from any header that still wraps.
    """
    module = sys.modules[__name__]
    source = module.CALIBRATION_SOURCE
    if source != "fallback":
        try:
            raw = json.loads(Path(source).read_text(encoding="utf-8"))
            measured = int(raw["header_chars_per_line"])
        except (OSError, json.JSONDecodeError, KeyError, TypeError, ValueError):
            measured = None
        lo, hi = PLAUSIBLE_HEADER_CHARS
        if measured is not None and lo <= measured <= hi:
            return measured
    return module.CHARS_PER_LINE - module.PROJECT_HEADER_GAP

#: How many work-experience entries the application-form expansion may cover. Higher than
#: `MAX_EXPERIENCE_ENTRIES` because forms are not page-constrained — the tile should
#: surface roles the one-pager dropped, not only the ones that made the resume.
MAX_EXPANDED_ENTRIES = 5

#: Soft character budget for one expanded entry's description field. LinkedIn's experience
#: description cap is 2,000; many ATS forms are similar or shorter. Advertised to the model
#: as a target band below this ceiling (see `expand._length_band`) so it does not optimise
#: right up to the edge and truncate on paste.
EXPAND_CHAR_LIMIT = 2000

#: Cap on how many skills the tile ever shows, applied after tier-sorting so "additional"
#: is what gets cut first — required/preferred skills should never be truncated away.
MAX_SKILLS_SUGGESTED = 24

#: Cap on how many candidates the skills pool sends to the model. JD-matched candidates are
#: sorted first (see `skills.build_pool`), so truncation only ever drops unmatched evidence.
SKILLS_POOL_LIMIT = 120

#: Target length for the cover letter's body, in words. Unlike every other length budget in
#: this file, this one is *not* derived from calibration: at ~350 words a letter occupies
#: well under half the page budget (`LINES_PER_PAGE * CHARS_PER_LINE`), so the page is never
#: the binding constraint and the word count is what actually shapes the output. The
#: one-page render check downstream is a safety net, not the driver.
COVER_WORD_TARGET = 350

#: Accepted word range for the body. Advertised to the model and enforced in code. The band
#: is deliberately wider below the target than above it: a slightly short letter reads
#: tight, a long one reads padded.
COVER_WORD_BAND = (300, 380)


class _ConfigModule(ModuleType):
    """Route legacy test monkeypatches through the process default context."""

    def __setattr__(self, name: str, value: Any) -> None:
        global _DEFAULT
        if name in _PATH_NAMES:
            _DEFAULT = replace(_DEFAULT, paths={**_DEFAULT.paths, name: value})
        elif name in _CALIBRATION_NAMES:
            values = list(_DEFAULT.calibration)
            values[_CALIBRATION_NAMES.index(name)] = value
            _DEFAULT = replace(_DEFAULT, calibration=tuple(values))
        elif name == "_ACTIVE_WORKSPACE_ID":
            _DEFAULT = replace(_DEFAULT, workspace_id=value)
        elif name == "TAG_ALIASES":
            _DEFAULT = replace(_DEFAULT, tag_aliases=value)
        elif name == "VERB_FAMILIES":
            _DEFAULT = replace(_DEFAULT, verb_families=value)
        else:
            super().__setattr__(name, value)


sys.modules[__name__].__class__ = _ConfigModule
