/**
 * Plain-language explanations for every template-analyzer issue code
 * (`template_analyze.py`; the list is `templateIssueCodes.json`, regenerated by
 * `scripts/export_issue_codes.py`). A vitest fails when a code has no entry here.
 */
export type IssueHelp = {
  title: string;
  why: string;
  /** Steps in Microsoft Word. */
  word?: string;
  /** Steps in Google Docs. */
  docs?: string;
  /** A fix inside this app (the mapping step, a re-upload). */
  app?: string;
  /** Offer "use a default template instead" (layout the app cannot edit). */
  useDefault?: boolean;
};

const TABLE_WORD =
  "Copy the resume text into a new blank document so it is ordinary single-column paragraphs, re-apply your fonts and headings, then save as .docx.";
const TABLE_DOCS =
  "Select everything in the table, copy it, paste it below the table with Edit → Paste without formatting, then delete the table (right-click → Delete table) and restyle the headings.";
const REMAP = "Fix the field mapping in the next step, or re-upload the file to start over.";
const LIST_WORD = "Select the lines and click Home → Bullets so each is a real Word list item.";
const LIST_DOCS = "Select the lines and click Format → Bullets & numbering → Bulleted list.";

const layout = (title: string, why: string): IssueHelp => ({
  title,
  why,
  word: TABLE_WORD,
  docs: TABLE_DOCS,
  useDefault: true,
});

const mapping = (title: string, why: string): IssueHelp => ({ title, why, app: REMAP });

export const TEMPLATE_ISSUES: Record<string, IssueHelp> = {
  // Layout the app cannot tailor safely.
  nested_tables: layout(
    "Tables inside tables",
    "Your resume puts a table inside another table. The app can only fill a plain single-column page (or one invisible layout table).",
  ),
  multiple_tables: layout(
    "More than one table",
    "Your resume uses several tables. Only one invisible layout table is supported, because tailoring changes line lengths and the tables would drift apart.",
  ),
  table_vertical_merge: layout(
    "Sidebar made with merged cells",
    "A column of your table spans several rows, which is how a sidebar is built. Sidebars can't be tailored without breaking the layout.",
  ),
  table_parallel_columns: layout(
    "Two or more columns side by side",
    "Your resume reads as parallel columns. Tailored text changes length, so side-by-side columns would stop lining up.",
  ),
  table_sidebar_bullets: layout(
    "Bullets in a sidebar column",
    "Bulleted text sits in a second table column (a sidebar). Only single-column bullets can be tailored.",
  ),
  table_sidebar_headings: layout(
    "Section headings in a sidebar",
    "A section heading shares a table row with other content, which is how sidebar layouts work. Headings need their own line.",
  ),
  table_no_headings: layout(
    "Table without section headings",
    "Your resume's table has no recognizable headings (Experience, Education…), so it looks like a data table rather than a resume.",
  ),
  textboxes: {
    title: "Text boxes or a sidebar",
    why: "Your resume puts text inside text boxes, usually for a sidebar or two-column design. The app can only edit single-column text.",
    word: "Click each text box border, cut its text (Ctrl+X), click outside the box and paste it as normal paragraphs, then delete the empty boxes.",
    docs: "Google Docs drawings can't be edited this way: rebuild the content as plain paragraphs, or upload the original Word file.",
    useDefault: true,
  },
  decorative_drawing: {
    title: "Images, icons or lines (kept as-is)",
    why: "Pictures, icons and drawn lines are kept exactly as they are. Only the words around them change when you tailor.",
  },
  too_short: {
    title: "Too little text to read",
    why: "The file needs at least your name and a contact line. It may be empty, a scan, or mostly images.",
    word: "Make sure the resume text is typed text, not a picture, then save as .docx again.",
    useDefault: true,
  },
  heading_formatting_mismatch: {
    title: "A heading looks different from the others",
    why: "This line reads like a section heading but is formatted differently from your other headings. Check whether it really is one.",
    word: "Give it the same font, size and bold/caps as your other headings (Home → Format Painter copies formatting).",
    docs: "Use Format → Paint format from another heading, then click this line.",
  },
  missing_experience: {
    title: "No Experience section",
    why: "No Experience heading was found. That is fine for a first resume: your Projects and other sections are still used. Add an Experience heading later to include jobs.",
    word: "Add a line such as EXPERIENCE formatted like your other headings, with at least one job below it.",
  },
  missing_contact: {
    title: "No contact line under your name",
    why: "The line after your name should hold your email, phone or links. It may be in the page header or missing.",
    word: "Put your email and phone on a normal line directly under your name (not in Insert → Header).",
    docs: "Move the contact line out of the header (double-click the header, cut, paste into the page).",
  },
  contact_unmapped_paragraph: {
    title: "Contact line kept as written",
    why: "A line in your contact block isn't an email, phone, location or link, so it is kept exactly as written.",
  },
  manual_bullets: {
    title: "Typed bullet characters",
    why: "Some bullets are typed characters (•, -, *) rather than a real list, so the app can't tell where each bullet starts.",
    word: LIST_WORD,
    docs: LIST_DOCS,
  },
  empty_experience: {
    title: "Experience section is empty",
    why: "The Experience heading has no job under it to use as a pattern for the others.",
    word: "Add at least one job (company, title, dates, bullets) under Experience, then upload again.",
  },
  experience_dates_not_detected: {
    title: "Job dates not found",
    why: "No job line has a date the app recognises, so every tailored job would lose its dates.",
    word: "Put dates like 'Jun 2024 – Aug 2024' on the company line, separated from the name by a tab.",
    app: "Or map the dates field by hand in the next step.",
  },
  experience_dates_partial: {
    title: "Some jobs have no dates",
    why: "Only some jobs have a recognised date; the others will show without one.",
    word: "Use the same date style on every job line.",
  },
  no_experience_bullets: {
    title: "Job bullets aren't a real list",
    why: "Experience bullets need to be real list items so each one can be rewritten separately.",
    word: LIST_WORD,
    docs: LIST_DOCS,
  },
  inline_title: {
    title: "Job title not on its own line",
    why: "No separate job-title line was found under the company line.",
    word: "Put the job title on its own line under each company, or map the title field in the next step.",
    app: REMAP,
  },
  no_education_bullets: {
    title: "Education details aren't a list",
    why: "The degree and detail lines under Education need to be real list items.",
    word: LIST_WORD,
    docs: LIST_DOCS,
  },
  education_bullets_not_list: {
    title: "Education line converted to a bullet",
    why: "An Education detail line isn't a list item; the app turns it into one in your template.",
  },
  empty_education: {
    title: "Education section is empty",
    why: "The Education heading has no school under it, so it will be left out.",
  },
  project_dates_not_detected: {
    title: "Project dates not found",
    why: "No project line has a recognised date, so every tailored project would lose its date.",
    word: "Put a date on each project line, after a tab, or map the date field in the next step.",
    app: REMAP,
  },
  project_dates_partial: {
    title: "Some projects have no date",
    why: "Only some projects have a recognised date; the others will show without one.",
  },
  no_project_bullets: {
    title: "Project bullets aren't a real list",
    why: "Project bullets need to be real list items so each one can be rewritten separately.",
    word: LIST_WORD,
    docs: LIST_DOCS,
  },
  skills_format: {
    title: "Skills lines in an unexpected format",
    why: "Skills lines should look like 'Languages: Python, SQL, Excel' so each group can be tailored.",
    word: "Write each skills line as a label, a colon, then items separated by commas.",
  },
  omit_education: {
    title: "No Education section",
    why: "No Education heading was found, so the tailored resume won't have one.",
  },
  omit_projects: {
    title: "No Projects section",
    why: "No Projects heading was found, so the tailored resume won't have one.",
  },
  omit_skills: {
    title: "No Skills section",
    why: "No Skills heading was found, so the tailored resume won't have one.",
  },
  experience_required: {
    title: "Nothing left to tailor",
    why: "Keep at least one of Experience, Projects or a list section switched on.",
    app: "Switch one of those sections back on in the mapping step.",
  },
  // Mapping checks (from the confirm step, not the document itself).
  hash_mismatch: {
    title: "File changed since it was analyzed",
    why: "The mapping was confirmed for a different file than the one being installed.",
    app: "Upload the file again and redo the mapping.",
  },
  bad_name: mapping("Name line not found", "The mapped name line no longer exists in the file."),
  bad_contact: mapping(
    "Contact line not found",
    "The mapped contact line no longer exists in the file.",
  ),
  bad_span: mapping("A mapped field is out of range", "A field points past the end of its line."),
  span_has_tab: mapping(
    "A field runs across a tab",
    "A mapped field includes a tab. Map dates to the text after the tab, not through it.",
  ),
  overlapping_spans: mapping(
    "Two fields claim the same text",
    "Two mapped fields overlap on the same line.",
  ),
  bad_bullet: mapping("A mapped bullet is missing", "A bullet the mapping points to is gone."),
  bullet_not_list: {
    title: "A mapped bullet isn't a list item",
    why: "The line mapped as a bullet isn't a real list item.",
    word: LIST_WORD,
    docs: LIST_DOCS,
    app: REMAP,
  },
  header_not_entry_start: mapping(
    "Entry line points at a bullet or blank line",
    "The line mapped as an entry header is a bullet or empty.",
  ),
  date_span_not_date_shaped: mapping(
    "A date field doesn't look like a date",
    "The text mapped as a date doesn't look like one. Check the mapping.",
  ),
  prototype_spans_multiple_entries: mapping(
    "Fields come from different entries",
    "The fields of the pattern entry were taken from different jobs or projects.",
  ),
  bad_heading_prototype: mapping(
    "Heading pattern not found",
    "The heading used as a pattern no longer exists in the file.",
  ),
  bad_detected_section: mapping(
    "A detected section is out of range",
    "A section heading the mapping refers to no longer exists.",
  ),
  spacer_donor_missing: {
    title: "A spacer line will be dropped",
    why: "A blank or rule line used for spacing has moved, so it will be left out of the template.",
  },
};

/** Explanation for `code`, or a generic one for a code this build doesn't know. */
export function issueHelp(code: string): IssueHelp {
  return (
    TEMPLATE_ISSUES[code] ?? {
      title: "Template issue",
      why: "The analyzer flagged something in this document; see the details.",
    }
  );
}
